### ISSUE TITLE
Trouble Installing WhereHows (Bootstrapping?)

### ISSUE THREAD

**Issue by dyaw-Drexel** [linkedin/datahub#1511]
On the final step of installing, running sudo python mce_cli.py produce -d bootstrap_mce.dat,
I am getting this error:

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8081): Max retries exceeded with url: /subjects/MetadataChangeEvent-value/versions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b430d7090>: Failed to establish a new connection: [Errno 111] Connection refused',))

the datahub-mce-consumer log says:

17:16:37.692 [main] WARN  org.apache.kafka.clients.ClientUtils - Couldn't resolve server broker:29092 from bootstrap.servers as DNS resolution failed for broker
Exception in thread "main" org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407)
        at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65)
        at org.apache.kafka.streams.processor.internals.DefaultKafkaClientSupplier.getAdminClient(DefaultKafkaClientSupplier.java:34)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:713)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:634)
        at org.apache.kafka.streams.KafkaStreams.<init>(KafkaStreams.java:544)
        at com.linkedin.metadata.kafka.MceStreamTask.main(MceStreamTask.java:55)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
        at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367)
        ... 6 more

This is on Ubuntu 18.04 server on an Azure VM. Any ideas?

**Comment by keremsahin1** [comment]
@dyaw-Drexel Thank you for your interest in trying Data Hub.
I also saw your message on Gitter channnel. In this case, your Kafka broker seems not alive after running quickstart docker-compose. Below is the relevant line: `Couldn't resolve server broker:29092`.

We need to figure out why Kafka is not booting up correctly. Do you see any errors during Kafka initialization from the docker logs? You can also just try to bring up only Kafka (and related containers) using docker-compose script under `docker/kafka/` folder. Please share any error message you get during the initialization of Kafka. Also, make sure to pull in latest changes from repo.

**Comment by dyaw-Drexel** [comment]
@keremsahin1 

Yep, there are some errors in the Kafka Docker logs:

`	sasl.kerberos.ticket.renew.jitter = 0.05,
	sasl.kerberos.ticket.renew.window.factor = 0.8,
	sasl.login.callback.handler.class = null,
	sasl.login.class = null,
	sasl.login.refresh.buffer.seconds = 300,
	sasl.login.refresh.min.period.seconds = 60,
	sasl.login.refresh.window.factor = 0.8,
	sasl.login.refresh.window.jitter = 0.05,
	sasl.mechanism = GSSAPI,
	security.protocol = PLAINTEXT,
	send.buffer.bytes = 131072,
	ssl.cipher.suites = null,
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1],
	ssl.endpoint.identification.algorithm = https,
	ssl.key.password = null,
	ssl.keymanager.algorithm = SunX509,
	ssl.keystore.location = null,
	ssl.keystore.password = null,
	ssl.keystore.type = JKS,
	ssl.protocol = TLS,
	ssl.provider = null,
	ssl.secure.random.implementation = null,
	ssl.trustmanager.algorithm = PKIX,
	ssl.truststore.location = null,
	ssl.truststore.password = null,
	ssl.truststore.type = JKS,
,
[main] WARN org.apache.kafka.clients.ClientUtils - Couldn't resolve server broker:29092 from bootstrap.servers as DNS resolution failed for broker,
[main] ERROR io.confluent.admin.utils.cli.KafkaReadyCommand - Error while running kafka-ready.,
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient,
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407),
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65),
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138),
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150),
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers,
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88),
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47),
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367),
	... 3 more,
Waiting for Kafka to be ready...,
[main] INFO org.apache.kafka.clients.admin.AdminClientConfig - AdminClientConfig values: ,
	bootstrap.servers = [broker:29092],
	client.dns.lookup = default,
	client.id = ,
	connections.max.idle.ms = 300000,
	metadata.max.age.ms = 300000,
	metric.reporters = [],
	metrics.num.samples = 2,
	metrics.recording.level = INFO,
	metrics.sample.window.ms = 30000,
	receive.buffer.bytes = 65536,
	reconnect.backoff.max.ms = 1000,
	reconnect.backoff.ms = 50,
	request.timeout.ms = 120000,
	retries = 5,
	retry.backoff.ms = 100,
	sasl.client.callback.handler.class = null,
	sasl.jaas.config = null,
	sasl.kerberos.kinit.cmd = /usr/bin/kinit,
	sasl.kerberos.min.time.before.relogin = 60000,
	sasl.kerberos.service.name = null,
	sasl.kerberos.ticket.renew.jitter = 0.05,
	sasl.kerberos.ticket.renew.window.factor = 0.8,
	sasl.login.callback.handler.class = null,
	sasl.login.class = null,
	sasl.login.refresh.buffer.seconds = 300,
	sasl.login.refresh.min.period.seconds = 60,
	sasl.login.refresh.window.factor = 0.8,
	sasl.login.refresh.window.jitter = 0.05,
	sasl.mechanism = GSSAPI,
	security.protocol = PLAINTEXT,
	send.buffer.bytes = 131072,
	ssl.cipher.suites = null,
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1],
	ssl.endpoint.identification.algorithm = https,
	ssl.key.password = null,
	ssl.keymanager.algorithm = SunX509,
	ssl.keystore.location = null,
	ssl.keystore.password = null,
	ssl.keystore.type = JKS,
	ssl.protocol = TLS,
	ssl.provider = null,
	ssl.secure.random.implementation = null,
	ssl.trustmanager.algorithm = PKIX,
	ssl.truststore.location = null,
	ssl.truststore.password = null,
	ssl.truststore.type = JKS,
,
[main] WARN org.apache.kafka.clients.ClientUtils - Couldn't resolve server broker:29092 from bootstrap.servers as DNS resolution failed for broker,
[main] ERROR io.confluent.admin.utils.cli.KafkaReadyCommand - Error while running kafka-ready.,
org.apache.kafka.common.KafkaException: Failed to create new KafkaAdminClient,
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:407),
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:65),
	at io.confluent.admin.utils.ClusterStatus.isKafkaReady(ClusterStatus.java:138),
	at io.confluent.admin.utils.cli.KafkaReadyCommand.main(KafkaReadyCommand.java:150),
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers,
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88),
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47),
	at org.apache.kafka.clients.admin.KafkaAdminClient.createInternal(KafkaAdminClient.java:367),
	... 3 more,`

**Comment by keremsahin1** [comment]
@dyaw-Drexel 
Sorry for missing this. Were you able to solve the issue finally?  Do you still need help?
