### ISSUE TITLE
 when login , Invalid username exceptions:

### ISSUE THREAD

**Issue by theseusyang** [linkedin/datahub#1588]
when login , Invalid username exceptions:
my username is datahub , password is datahub
play.api.UnexpectedException: Unexpected exception[InvalidParameterException: Invalid username: datahub]
datahub-frontend        | 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:247)
datahub-frontend        | 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:176)
datahub-frontend        | 	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:363)
datahub-frontend        | 	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:361)
datahub-frontend        | 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
datahub-frontend        | 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
datahub-frontend        | 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
datahub-frontend        | 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
datahub-frontend        | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
datahub-frontend        | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
datahub-frontend        | 	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
datahub-frontend        | 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
datahub-frontend        | 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
datahub-frontend        | 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
datahub-frontend        | 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
datahub-frontend        | 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
datahub-frontend        | 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
datahub-frontend        | 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
datahub-frontend        | 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
datahub-frontend        | Caused by: java.security.InvalidParameterException: Invalid username: datahub
datahub-frontend        | 	at controllers.api.v1.User.getLoggedInUser(User.java:52)
datahub-frontend        | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:772)
datahub-frontend        | 	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:772)
datahub-frontend        | 	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
datahub-frontend        | 	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
datahub-frontend        | 	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
datahub-frontend        | 	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
datahub-frontend        | 	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
datahub-frontend        | 	at play.mvc.Security$AuthenticatedAction.call(Security.java:69)
datahub-frontend        | 	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
datahub-frontend        | 	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
datahub-frontend        | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
datahub-frontend        | 	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
datahub-frontend        | 	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
datahub-frontend        | 	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
datahub-frontend        | 	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
datahub-frontend        | 	at scala.concurrent.impl.Future$.apply(Future.scala:31)
datahub-frontend        | 	at scala.concurrent.Future$.apply(Future.scala:494)
datahub-frontend        | 	at play.core.j.JavaAction.apply(JavaAction.scala:138)
datahub-frontend        | 	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:96)
datahub-frontend        | 	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:89)
datahub-frontend        | 	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
datahub-frontend        | 	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
datahub-frontend        | 	at scala.util.Try$.apply(Try.scala:192)
datahub-frontend        | 	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:174)
datahub-frontend        | 	at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:170)
datahub-frontend        | 	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
datahub-frontend        | 	at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:207)
datahub-frontend        | 	at play.core.server.AkkaHttpServer$$anonfun$14.apply(AkkaHttpServer.scala:357)
datahub-frontend        | 	at play.core.server.

**Comment by liaicheng** [comment]
I had same issue, no found useful method. I need help, too

**Comment by keremsahin1** [comment]
Can you please share a dump of your MySQL DB? Do you have any records?

**Comment by liaicheng** [comment]
For my issue, i do as bellow two steps: 
1, make sure mysql docker work well, you can test with the connection localhost:3306.
2, make sure  init.sql to execute. watch your datahub database.

**Comment by keremsahin1** [comment]
@liaicheng 
What error were you getting when you use `volumes` config in mysql docker-compose? I guess you're deploying MySQL container individually (https://github.com/linkedin/datahub/tree/master/docker/mysql), not as part of quickstart.

**Comment by liaicheng** [comment]
Error occur when i connect MySQL with Navicat. At first, I didn't found out the real reason, and change deploying MySQL container individually, issue occur. I guess you are right.

**Comment by jywadhwani** [comment]
@liaicheng can you share some updates on the progress? Were you able to get rid of the exception?

**Comment by Nickko04** [comment]
Not able to solve the problem using @liaicheng method :
SQL Container logs attached 

---------------
root@SAXOINDEV8440:~/datahub-master/docker/mysql# docker logs 250996d9e490
2020-03-31 06:50:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
2020-03-31 06:50:08+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-03-31 06:50:08+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.29-1debian10 started.
2020-03-31T06:50:09.389098Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2020-03-31T06:50:09.391034Z 0 [Note] mysqld (mysqld 5.7.29) starting as process 1 ...
2020-03-31T06:50:09.411945Z 0 [Note] InnoDB: PUNCH HOLE support available
2020-03-31T06:50:09.411970Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-03-31T06:50:09.411973Z 0 [Note] InnoDB: Uses event mutexes
2020-03-31T06:50:09.411975Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2020-03-31T06:50:09.411977Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-03-31T06:50:09.411979Z 0 [Note] InnoDB: Using Linux native AIO
2020-03-31T06:50:09.417626Z 0 [Note] InnoDB: Number of pools: 1
2020-03-31T06:50:09.420356Z 0 [Note] InnoDB: Using CPU crc32 instructions
2020-03-31T06:50:09.422420Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-03-31T06:50:09.431003Z 0 [Note] InnoDB: Completed initialization of buffer pool
2020-03-31T06:50:09.433015Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-03-31T06:50:09.495926Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2020-03-31T06:50:09.588698Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-03-31T06:50:09.588934Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-03-31T06:50:09.592310Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2020-03-31T06:50:09.593039Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2020-03-31T06:50:09.593050Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2020-03-31T06:50:09.593670Z 0 [Note] InnoDB: Waiting for purge to start
2020-03-31T06:50:09.644305Z 0 [Note] InnoDB: 5.7.29 started; log sequence number 12480999
2020-03-31T06:50:09.644718Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2020-03-31T06:50:09.645345Z 0 [Note] Plugin 'FEDERATED' is disabled.
2020-03-31T06:50:09.800791Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2020-03-31T06:50:09.800811Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2020-03-31T06:50:09.803585Z 0 [Warning] CA certificate ca.pem is self signed.
2020-03-31T06:50:09.804831Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2020-03-31T06:50:09.806552Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2020-03-31T06:50:09.806881Z 0 [Note] IPv6 is available.
2020-03-31T06:50:09.807071Z 0 [Note]   - '::' resolves to '::';
2020-03-31T06:50:09.807107Z 0 [Note] Server socket created on IP: '::'.
2020-03-31T06:50:09.827992Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2020-03-31T06:50:09.866332Z 0 [Note] InnoDB: Buffer pool(s) load completed at 200331  6:50:09
2020-03-31T06:50:09.896440Z 0 [Note] Event Scheduler: Loaded 0 events
2020-03-31T06:50:09.896805Z 0 [Note] mysqld: ready for connections.
Version: '5.7.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2020-03-31T06:50:23.475937Z 2 [Note] Got timeout reading communication packets
2020-03-31T06:52:37.646885Z 6 [Note] Got packets out of order
2020-03-31T06:52:37.845495Z 5 [Note] Got packets out of order
2020-03-31T06:52:42.870111Z 7 [Note] Got packets out of order
2020-03-31T06:52:47.293519Z 8 [Note] Got packets out of order
2020-03-31T06:52:57.298462Z 9 [Note] Got timeout reading communication packets
2020-03-31T07:04:45.850866Z 17 [Note] Got packets out of order
2020-03-31T07:04:46.450705Z 18 [Note] Got packets out of order
2020-03-31T07:04:47.076743Z 19 [Note] Got an error reading communication packets
2020-03-31T07:04:47.802501Z 20 [Note] Got an error reading communication packets
2020-03-31T07:04:48.424253Z 21 [Note] Got an error reading communication packets
2020-03-31T07:04:48.962575Z 22 [Note] Got an error reading communication packets
2020-03-31T07:04:49.675369Z 23 [Note] Got an error reading communication packets
2020-03-31T07:04:50.281387Z 24 [Note] Got an error reading communication packets
2020-03-31T07:04:50.775369Z 25 [Note] Got an error reading communication packets
2020-03-31T07:04:54.956394Z 26 [Note] Got packets out of order
2020-03-31T07:04:55.676202Z 27 [Note] Got packets out of order
2020-03-31T07:04:56.322982Z 28 [Note] Got an error reading communication packets
2020-03-31T07:04:57.028085Z 29 [Note] Got an error reading communication packets
2020-03-31T07:04:57.755632Z 30 [Note] Got an error reading communication packets
2020-03-31T07:04:58.347367Z 31 [Note] Got an error reading communication packets
2020-03-31T07:04:58.943065Z 32 [Note] Got an error reading communication packets
2020-03-31T07:04:59.439530Z 33 [Note] Got an error reading communication packets

**Comment by mars-lan** [comment]
Assuming the issue has been resolved. Feel free to reopen otherwise.

@Nickko04's issue is separately tracked by https://github.com/linkedin/datahub/issues/1620
