### ISSUE TITLE
metadata ingestion example throws avro encoding error.

### ISSUE THREAD

**Issue by jhsenjaliya** [linkedin/datahub#1604]
**Describe the bug**
running the metadata ingestion throws avro encoding error.

**To Reproduce**
follow the exxample steps from here: https://github.com/linkedin/datahub/tree/master/metadata-ingestion and you should see the following error

` mce-cli git:(master) python mce_cli.py produce -d bootstrap_mce.dat
Producing MetadataChangeEvent records to topic MetadataChangeEvent. ^c to exit.
Traceback (most recent call last):
  File "mce_cli.py", line 108, in <module>
    main(parser.parse_args())
  File "mce_cli.py", line 88, in main
    produce(conf, args.data_file, args.schema_record)
  File "mce_cli.py", line 32, in produce
    producer.produce(topic=topic, value=content)
  File "/Users/jsenjaliya/Library/Python/3.7/lib/python/site-packages/confluent_kafka/avro/__init__.py", line 80, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/Users/jsenjaliya/Library/Python/3.7/lib/python/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 107, in encode_record_with_schema
    schema_id = self.registry_client.register(subject, schema)
  File "/Users/jsenjaliya/Library/Python/3.7/lib/python/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 217, in register
    body = {'schema': json.dumps(avro_schema.to_json())}
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type mappingproxy is not JSON serializable`

**Expected behavior**
should have ingested some sample records.

**Desktop (please complete the following information):**
 - OS: MAC 10.14

**Additional context**
avro python library is not compatible with confluent kafka library.

**Comment by animeshinvinci** [comment]
I also face this issue.. it's python 3.7 version compatibility with python Avro lib.
please let me know if you need this fix
@jhsenjaliya

**Comment by mars-lan** [comment]
@animeshinvinci @jhsenjaliya has already submitted a PR fixing this: https://github.com/linkedin/datahub/pull/1605 Could you check and see if it's the same fix you have?
