### ISSUE TITLE
metadata-ingestion scripts throw avro.io.AvroTypeException

### ISSUE THREAD

**Issue by cobolbaby** [linkedin/datahub#1724]
**Describe the bug**

```
dev@docker-build-1:/opt/datahub/metadata-ingestion/mysql-etl$ vi mysql_etl.py
... 
dev@docker-build-1:/opt/datahub/metadata-ingestion/mysql-etl$ python3 mysql_etl.py 
Traceback (most recent call last):
  File "mysql_etl.py", line 78, in <module>
    build_mysql_dataset_mce(dataset_name, schema, schema_version)
  File "mysql_etl.py", line 42, in build_mysql_dataset_mce
    produce_mysql_dataset_mce(mce)
  File "mysql_etl.py", line 54, in produce_mysql_dataset_mce
    producer.produce(topic=KAFKATOPIC, value=mce)
  File "/home/dev/.local/lib/python3.7/site-packages/confluent_kafka/avro/__init__.py", line 99, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/home/dev/.local/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 118, in encode_record_with_schema
    return self.encode_record_with_schema_id(schema_id, record, is_key=is_key)
  File "/home/dev/.local/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 152, in encode_record_with_schema_id
    writer(record, outf)
  File "/home/dev/.local/lib/python3.7/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 86, in <lambda>
    return lambda record, fp: writer.write(record, avro.io.BinaryEncoder(fp))
  File "/home/dev/.local/lib/python3.7/site-packages/avro/io.py", line 809, in write
    raise AvroTypeException(self.writer_schema, datum)
avro.io.AvroTypeException: The datum {'auditHeader': None, 'proposedSnapshot': ('com.linkedin.pegasus2avro.metadata.snapshot.DatasetSnapshot', {'urn': 'urn:li:dataset:(urn:li:dataPlatform:mysql,factory_board.c_agent_type_define,PROD)', 'aspects': [{'owners': [{'owner': 'urn:li:corpuser:datahub', 'type': 'DATAOWNER'}], 'lastModified': {'time': 0, 'actor': 'urn:li:corpuser:datahub'}}, {'schemaName': 'factory_board.c_agent_type_define', 'platform': 'urn:li:dataPlatform:mysql', 'version': 10, 'created': {'time': 1594184660.5085697, 'actor': 'urn:li:corpuser:datahub'}, 'lastModified': {'time': 1594184660.5085697, 'actor': 'urn:li:corpuser:datahub'}, 'hash': '', 'platformSchema': {'tableSchema': "[('Id', 'bigint(20)', 'NO', 'PRI', None, 'auto_increment'), ('Name', 'varchar(64)', 'YES', '', None, ''), ('Remark1', 'varchar(128)', 'YES', '', None, ''), ('Remark2', 'varchar(128)', 'YES', '', None, ''), ('CreateTime', 'datetime', 'YES', '', None, ''), ('UpdateTime', 'datetime', 'YES', '', None, ''), ('LifeCycleStatus', 'int(11)', 'NO', '', '1', '')]"}, 'fields': [{'fieldPath': 'Id', 'nativeDataType': 'bigint(20)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'Name', 'nativeDataType': 'varchar(64)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'Remark1', 'nativeDataType': 'varchar(128)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'Remark2', 'nativeDataType': 'varchar(128)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'CreateTime', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'UpdateTime', 'nativeDataType': 'datetime', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}, {'fieldPath': 'LifeCycleStatus', 'nativeDataType': 'int(11)', 'type': {'type': {'com.linkedin.pegasus2avro.schema.StringType': {}}}}]}]}), 'proposedDelta': None} is not an example of the schema {
  "type": "record",
  "name": "MetadataChangeEvent",
  "namespace": "com.linkedin.pegasus2avro.mxe",
...
```
Are there any special requirements for the configured MySQL database?

**Comment by cobolbaby** [comment]
Modify the dependent packages:

```
confluent-kafka[avro]==1.4.0
```
