### ISSUE TITLE
There are some errors when I check

### ISSUE THREAD

**Issue by HondaHsu2020** [linkedin/datahub#1943]
Hi， when I run this command:docker logs datahub-frontend, there are errors :

1.
```
Caused by: java.lang.RuntimeException: com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://datahub-gms:8080/corpUsers/($params:(),name:datahub)
        at controllers.api.v1.User.getLoggedInUser(User.java:51)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:791)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$12$$anonfun$apply$12.apply(Routes.scala:791)
        at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
```

2.
```
Caused by: com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server forURI http://datahub-gms:8080/corpUsers/($params:(),name:datahub)
        at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:135)
        at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
```

3.
```
Caused by: com.linkedin.r2.RetriableRequestException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: datahub-gms/172.21.0.8:8080**
        at com.linkedin.r2.transport.http.client.common.ChannelPoolLifecycle.onError(ChannelPoolLifecycle.java:142)
        at com.linkedin.r2.transport.http.client.common.ChannelPoolLifecycle.lambda$create$0(ChannelPoolLifecycle.java:97)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
```
4. when I run docker logs elasticsearch,there are some errors:
```
[2020-10-13T11:03:11,194][INFO ][o.e.m.j.JvmGcMonitorService] [cZfAt1Y] [gc][7] overhead, spent [473ms] collecting in the last [1.4s]
[2020-10-13T11:03:14,465][ERROR][o.e.x.m.c.i.IndexRecoveryCollector] [cZfAt1Y] collector [index-recovery] **failed to collect data**
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.admin.indices.recovery.TransportRecoveryAction.checkGlobalBlock(TransportRecoveryAction.java:114) ~[elasticsearch-5.6.8.jar:5.6.8]

[2020-10-13T11:03:14,674][ERROR][o.e.x.m.c.i.IndexStatsCollector] [cZfAt1Y] collector [index-stats] failed to collect data
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.checkGlobalBlock(TransportIndicesStatsAction.java:70) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.admin.indices.stats.TransportIndicesStatsAction.checkGlobalBlock(TransportIndicesStatsAction.java:47) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.<init>(TransportBroadcastByNodeAction.java:256) ~[elasticsearch-5.6.8.jar:5.6.8]
```

Hi, How can I solve these problems

**Comment by mars-lan** [comment]
```
[2020-10-13T11:03:14,674][ERROR][o.e.x.m.c.i.IndexStatsCollector] [cZfAt1Y] collector [index-stats] failed to collect data
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.6.8.jar:5.6.8]
```

Seems like your Elasticsearch docker is down? Did you allocate enough memory to your docker daemon as stated in the [Quickstart guide](https://github.com/linkedin/datahub/blob/master/docs/quickstart.md)

**Comment by HondaHsu2020** [comment]
> ```
> [2020-10-13T11:03:14,674][ERROR][o.e.x.m.c.i.IndexStatsCollector] [cZfAt1Y] collector [index-stats] failed to collect data
> org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
> at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.6.8.jar:5.6.8]
> ```
> 
> Seems like your Elasticsearch docker is down? Did you allocate enough memory to your docker daemon as stated in the [Quickstart guide](https://github.com/linkedin/datahub/blob/master/docs/quickstart.md)

Previously, the memory was 8g. Now, docker compose - P datahub, stop, add memory to 12g, and execute docker - compose - P datahub up. However, after restarting docker,and View log and run the command : **docker logs datahub-gms**.
**at First ,the log as follows:**

“2020-10-16 08:39:01.360:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@3339ad8e{Open source GMS,/,file:///tmp/jetty-0_0_0_0-8080-war_war-_-any-3132238000727514031.dir/webapp/,AVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
2020-10-16 08:39:01.392:INFO:oejs.AbstractConnector:main: Started ServerConnector@5fdef03a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2020-10-16 08:39:01.393:INFO:oejs.Server:main: Started @64380ms
08:39:58.577 [qtp626202354-10] INFO  c.l.r.s.c.ResourceMethodConfigProviderImpl - RestLi MethodLevel Configuration for property timeoutMs sorted by priority - first match gets applied:
*.* = 0

08:39:58.719 [qtp626202354-10] INFO  c.l.r.s.c.ResourceMethodConfigProviderImpl - RestLi MethodLevel Configuration for property timeoutMs sorted by priority - first match gets applied:
*.* = 0

08:39:58.725 [qtp626202354-10] INFO  c.l.r.s.c.ResourceMethodConfigProviderImpl - RestLi MethodLevel Configuration for property timeoutMs sorted by priority - first match gets applied:
*.* = 0

08:39:59.841 [qtp626202354-10] INFO  c.l.parseq.TaskDescriptorFactory - No provider found for TaskDescriptor, falling back to DefaultTaskDescriptor
**08:40:00.510 [qtp626202354-17] ERROR c.l.metadata.dao.browse.ESBrowseDAO - Browse query failed: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]**  ”

**Secondly，I run the command "docker logs elasticsearch", the log as follows:**

“ [2020-10-16T08:37:45,339][INFO ][o.e.n.Node               ] [cZfAt1Y] started
[2020-10-16T08:37:47,446][INFO ][o.e.m.j.JvmGcMonitorService] [cZfAt1Y] [gc][5] overhead, spent [326ms] collecting in the last [1.1s]
**[2020-10-16T08:37:52,838][ERROR][o.e.x.m.c.i.IndexRecoveryCollector] [cZfAt1Y] collector [index-recovery] failed to collect data
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
        at org.elasticsearch.cluster.block.ClusterBlocks.globalBlockedException(ClusterBlocks.java:165) ~[elasticsearch-5.6.8.jar:5.6.8]
        at** org.elasticsearch.action.admin.indices.recovery.TransportRecoveryAction.checkGlobalBlock(TransportRecoveryAction.java:114) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.admin.indices.recovery.TransportRecoveryAction.checkGlobalBlock(TransportRecoveryAction.java:52) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction$AsyncAction.<init>(TransportBroadcastByNodeAction.java:256) ~[elasticsearch-5.6.8.jar:5.6.8]
        at org.elasticsearch.action.support.broadcast.node.TransportBroadcastByNodeAction.doExecute(TransportBroadcastByNodeAction.java:234) ~[elasticsearch-5.6.8.jar:5.6.8]

....................

type using the [Content-Type] header.
[2020-10-16T08:37:59,330][WARN ][o.e.d.r.RestController   ] Content type detection for rest requests is deprecated. Specify the contenttype using the [Content-Type] header.
[2020-10-16T08:38:09,454][INFO ][o.e.m.j.JvmGcMonitorService] [cZfAt1Y] [gc][young][26][4] duration [878ms], collections [1]/[1.6s], total [878ms]/[1.6s], memory [313.4mb]->[175.1mb]/[990.7mb], all_pools {[young] [263.1mb]->[1.3mb]/[266.2mb]}{[survivor] [33.2mb]->[33.2mb]/[33.2mb]}{[old] [17mb]->[140.5mb]/[691.2mb]}
[2020-10-16T08:38:09,454][WARN ][o.e.m.j.JvmGcMonitorService] [cZfAt1Y] [gc][26] overhead, spent [878ms] collecting in the last [1.6s]
[2020-10-16T08:38:19,069][INFO ][o.e.c.r.a.AllocationService] [cZfAt1Y] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.monitoring-kibana-6-2020.10.13][0], [.monitoring-es-6-2020.10.13][0]] ...]).
[2020-10-16T08:38:33,770][INFO ][o.e.m.j.JvmGcMonitorService] [cZfAt1Y] [gc][50] overhead, spent [350ms] collecting in the last [1.1s]  ”

**At last ,I can't see the demo on browse,when I press the query button，I only can see the result: An error occurred. Please try again shortly.** 。
I need your help ！

**Comment by mars-lan** [comment]
Looks like elasticsearch index still failed to start for whatever reason

```
failed to collect data
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [SERVICE_UNAVAILABLE/1/state not recovered / initialized];
```

Could you [nuke your docker environment](https://github.com/linkedin/datahub/blob/master/docs/debugging.md#ive-messed-up-my-docker-setup-how-do-i-start-from-scratch) and start from scratch again? I just checked out HEAD and tried from a clean slate and it worked as expected.

**Comment by mars-lan** [comment]
Assuming this has been resolved. Feel free to reopen otherwise.
