### ISSUE TITLE
how ingestion oracle metadata into datahub?

### ISSUE THREAD

**Issue by truezxd** [linkedin/datahub#2029]
pip install cx_oracle
install oracle  instantclient_11_2

vi oracle_etl.py
from common import run
# See https://github.com/PyMySQL/PyMySQL for more details
URL = 'oracle://system:oracle@10.9.28.51:1521/orcl' # e.g. mysql+pymysql://username:password@hostname:port
OPTIONS = {"encoding": "utf8"} # e.g. {"encoding": "latin1"}
PLATFORM = 'oracle'
run(URL, OPTIONS, PLATFORM)

python3 oracle_etl.py   
error :
Traceback (most recent call last):
  File "oracle_etl.py", line 8, in <module>
    run(URL, OPTIONS, PLATFORM)
  File "/home/datahub/datahub/metadata-ingestion/sql-etl/common.py", line 111, in run
    produce_dataset_mce(mce, kafka_config)
  File "/home/datahub/datahub/metadata-ingestion/sql-etl/common.py", line 100, in produce_dataset_mce
    producer.produce(topic=kafka_config.kafka_topic, key=mce['proposedSnapshot'][1]['urn'], value=mce)
  File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/__init__.py", line 99, in produce
    value = self._serializer.encode_record_with_schema(topic, value_schema, value)
  File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/serializer/message_serializer.py", line 108, in encode_record_with_schema
    schema_id = self.registry_client.register(subject, schema)
  File "/root/.local/lib/python3.6/site-packages/confluent_kafka/avro/cached_schema_registry_client.py", line 225, in register
    raise ClientError("Unable to register schema. Error code:" + str(code))
confluent_kafka.avro.error.ClientError: Unable to register schema. Error code:504

before this action ,mysql_etl is success!  please help!!!

**Comment by truezxd** [comment]
reason:  config env network  proxy
