### ISSUE TITLE
Unable to ingest data from BigQuery sink

### ISSUE THREAD

**Issue by user5651** [linkedin/datahub#2153]
I've followed the [Quickstart](https://github.com/linkedin/datahub/blob/master/docs/quickstart.md) guide and loaded sample data. The UI is up and running on port 9001 so all good there. Now I want to ingest data from my BigQuery instance but I keep getting an error related to SQLAlchemy. I've tried authenticating with gcloud but no luck.

Can anyone help with this? Happy to provide more info it'll help.

Full log:

```
(venv) root@datahub-test:~/datahub/metadata-ingestion# pip freeze
appdirs==1.4.4
attrs==20.3.0
avro-gen @ https://api.github.com/repos/rbystrit/avro_gen/tarball/master
avro-python3==1.10.1
bcrypt==3.2.0
black==20.8b1
cached-property==1.5.2
cachetools==4.2.1
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
click==7.1.2
confluent-kafka==1.6.0
coverage==5.5
cryptography==3.4.6
-e git+https://github.com/linkedin/datahub.git@cda1ce458974dda1cdc59b2c0957369e9524ea5e#egg=datahub&subdirectory=metadata-ingestion
deepdiff==5.2.3
distro==1.5.0
docker==4.4.4
docker-compose==1.28.5
dockerpty==0.4.1
docopt==0.6.2
fastavro==1.3.2
flake8==3.8.4
frozendict==1.2
future==0.18.2
google-api-core==1.26.0
google-auth==1.27.0
google-cloud-bigquery==2.10.0
google-cloud-core==1.6.0
google-crc32c==1.1.2
google-resumable-media==1.2.0
googleapis-common-protos==1.53.0
grpcio==1.36.0
idna==2.10
iniconfig==1.1.1
isort==5.7.0
jsonschema==3.2.0
mccabe==0.6.1
mypy==0.812
mypy-extensions==0.4.3
ordered-set==4.0.2
packaging==20.9
paramiko==2.7.2
pathspec==0.8.1
pkg-resources==0.0.0
pluggy==0.13.1
proto-plus==1.14.2
protobuf==3.15.3
py==1.10.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybigquery==0.5.0
pycodestyle==2.6.0
pycparser==2.20
pydantic==1.8
pyflakes==2.2.0
PyMySQL==1.0.2
PyNaCl==1.4.0
pyparsing==2.4.7
pyrsistent==0.17.3
pytest==6.2.2
pytest-cov==2.11.1
pytest-docker==0.10.1
python-dotenv==0.15.0
python-tds==1.10.0
python3-ldap==0.9.8.4
pytz==2021.1
PyYAML==5.4.1
regex==2020.11.13
requests==2.25.1
rsa==4.7.2
six==1.15.0
SQLAlchemy==1.3.23
sqlalchemy-pytds==0.3.1
sqlalchemy-stubs==0.4
texttable==1.6.3
toml==0.10.2
typed-ast==1.4.2
typing-extensions==3.7.4.3
tzlocal==2.1
urllib3==1.26.3
websocket-client==0.57.0
(venv) root@datahub-test:~/datahub/metadata-ingestion# ls /
bigquery.yml  boot  etc   lib    lib64   lost+found  mnt  proc  run                  sbin  srv  tmp  var
bin           dev   home  lib32  libx32  media       opt  root  sa_credentials.json  snap  sys  usr
(venv) root@datahub-test:~/datahub/metadata-ingestion# cat /bigquery.yml
source:
  type: bigquery
  config:
    project_id: <PROJECT_ID>
    options:
      credential_path: "/sa_credentials.json"
sink:
  type: console
(venv) root@datahub-test:~/datahub/metadata-ingestion# datahub ingest -c /bigquery.yml
[2021-03-02 09:15:27,558] DEBUG    {datahub.entrypoints:64} - Using config: {'source': {'type': 'bigquery', 'config': {'project_id': '<PROJECT_ID>', 'options': {'credential_path': '/sa_credentials.json'}}}, 'sink': {'type': 'console'}}
[2021-03-02 09:15:27,558] DEBUG    {datahub.ingestion.run.pipeline:63} - Source type:bigquery,<class 'datahub.ingestion.source.bigquery.BigQuerySource'> configured
[2021-03-02 09:15:27,558] DEBUG    {datahub.ingestion.run.pipeline:69} - Sink type:console,<class 'datahub.ingestion.sink.console.ConsoleSink'> configured
[2021-03-02 09:15:27,558] DEBUG    {datahub.ingestion.source.sql_common:152} - sql_alchemy_url=bigquery://<PROJECT_ID>
[2021-03-02 09:15:27,773] DEBUG    {google.auth._default:203} - Checking None for explicit credentials as part of auth process...
[2021-03-02 09:15:27,774] DEBUG    {google.auth._default:181} - Checking Cloud SDK credentials as part of auth process...
[2021-03-02 09:15:27,774] DEBUG    {google.auth._default:187} - Cloud SDK credentials not found on disk; not using them
[2021-03-02 09:15:27,774] DEBUG    {google.auth._default:223} - Checking for App Engine runtime as part of auth process...
[2021-03-02 09:15:27,775] DEBUG    {google.auth._default:234} - No App Engine library was found so cannot authentication via App Engine Identity Credentials.
[2021-03-02 09:15:27,776] DEBUG    {google.auth.transport._http_client:104} - Making request: GET http://169.254.169.254
[2021-03-02 09:15:27,778] DEBUG    {google.auth.transport._http_client:104} - Making request: GET http://metadata.google.internal/computeMetadata/v1/project/project-id
Traceback (most recent call last):
  File "/root/datahub/metadata-ingestion/venv/bin/datahub", line 11, in <module>
    load_entry_point('datahub', 'console_scripts', 'datahub')()
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/datahub/metadata-ingestion/src/datahub/entrypoints.py", line 70, in ingest
    pipeline.run()
  File "/root/datahub/metadata-ingestion/src/datahub/ingestion/run/pipeline.py", line 81, in run
    for wu in self.source.get_workunits():
  File "/root/datahub/metadata-ingestion/src/datahub/ingestion/source/sql_common.py", line 153, in get_workunits
    engine = create_engine(url, **sql_config.options)
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 520, in create_engine
    return strategy.create(*args, **kwargs)
  File "/root/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 164, in create
    raise TypeError(
TypeError: Invalid argument(s) 'credential_path' sent to create_engine(), using configuration BigQueryDialect/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
(venv) root@datahub-test:~/datahub/metadata-ingestion# 
```

**Comment by hsheth2** [comment]
Thanks for letting us know @user5651 - I'm working on a fix for this right now.

Part of the issue was a small typo in the readme - it should've been `credentials_path`, with an 's' at the end of credentials. There's also a second issue around the schema naming, which I'm working through now.

**Comment by hsheth2** [comment]
Hi @user5651: PR #2161 should fix this issue. Let me know if you have any issues with it 😄

**Comment by user5651** [comment]
Thanks for the prompt response @hsheth2! I'm not very familiar with Github so maybe I did something wrong but I cloned your repo, set up Datahu, ran the same command to ingest from BigQuery and got the below error. Maybe this is just me though.

`(venv) root@datahub-test:/tmp/datahub/metadata-ingestion# datahub ingest -c /bigquery.yml
[2021-03-03 10:39:04,078] DEBUG    {datahub.entrypoints:64} - Using config: {'source': {'type': 'bigquery', 'config': {'project_id': '<PROJECT_ID>', 'options': {'credentials_path': '/sa_credentials.json'}}}, 'sink': {'type': 'console'}}
[2021-03-03 10:39:04,079] DEBUG    {datahub.ingestion.run.pipeline:63} - Source type:bigquery,<class 'datahub.ingestion.source.bigquery.BigQuerySource'> configured
[2021-03-03 10:39:04,079] DEBUG    {datahub.ingestion.run.pipeline:69} - Sink type:console,<class 'datahub.ingestion.sink.console.ConsoleSink'> configured
[2021-03-03 10:39:04,079] DEBUG    {datahub.ingestion.source.sql_common:152} - sql_alchemy_url=bigquery://mb-<PROJECT_ID>
/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/google/cloud/bigquery/client.py:444: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(
Traceback (most recent call last):
  File "/tmp/datahub/metadata-ingestion/venv/bin/datahub", line 11, in <module>
    load_entry_point('datahub', 'console_scripts', 'datahub')()
  File "/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/datahub/metadata-ingestion/src/datahub/entrypoints.py", line 70, in ingest
    pipeline.run()
  File "/tmp/datahub/metadata-ingestion/src/datahub/ingestion/run/pipeline.py", line 81, in run
    for wu in self.source.get_workunits():
  File "/tmp/datahub/metadata-ingestion/src/datahub/ingestion/source/sql_common.py", line 155, in get_workunits
    database = sql_config.database
AttributeError: 'BigQueryConfig' object has no attribute 'database'
(venv) root@datahub-test:/tmp/datahub/metadata-ingestion#`

**Comment by hsheth2** [comment]
@user5651 the linked PR hasn't been merged yet, so you'll need to check it out from the branch:
```sh
git fetch origin pull/2161/head:bigquery
git checkout bigquery
# to restore afterwards, use git checkout master
```

Alternatively, you could just wait until #2161 gets merged in.

**Comment by user5651** [comment]
Ah yes that makes sense, thanks for the info @hsheth2!

I've followed your instructions and can confirm that Datahub is able to access BigQuery now. Nice work!

Unfortunately I'm getting another error during the ingestion of data from the BigQuery sink. I think this is related to a table that has repeated, nested datatypes. Should I open a new issue?

Log snippet:
```
Traceback (most recent call last):
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 89, in _compiler_dispatch
    meth = getter(visitor)
AttributeError: 'GenericTypeCompiler' object has no attribute 'visit_JSON'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/test2/datahub/metadata-ingestion/venv/bin/datahub", line 11, in <module>
    load_entry_point('datahub', 'console_scripts', 'datahub')()
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/tmp/test2/datahub/metadata-ingestion/src/datahub/entrypoints.py", line 70, in ingest
    pipeline.run()
  File "/tmp/test2/datahub/metadata-ingestion/src/datahub/ingestion/run/pipeline.py", line 81, in run
    for wu in self.source.get_workunits():
  File "/tmp/test2/datahub/metadata-ingestion/src/datahub/ingestion/source/sql_common.py", line 199, in get_workunits
    schema_metadata = get_schema_metadata(
  File "/tmp/test2/datahub/metadata-ingestion/src/datahub/ingestion/source/sql_common.py", line 135, in get_schema_metadata
    type=get_column_type(sql_report, dataset_name, column["type"]),
  File "/tmp/test2/datahub/metadata-ingestion/src/datahub/ingestion/source/sql_common.py", line 120, in get_column_type
    dataset_name, f"unable to map type {column_type} to metadata schema"
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 622, in __str__
    return str(self.compile())
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 605, in compile
    return dialect.type_compiler.process(self)
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/sql/compiler.py", line 402, in process
    return type_._compiler_dispatch(self, **kw)
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    util.raise_(
  File "/tmp/test2/datahub/metadata-ingestion/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.UnsupportedCompilationError: Compiler <sqlalchemy.sql.compiler.GenericTypeCompiler object at 0x7f1af1429fd0> can't render element of type <class 'sqlalchemy.sql.sqltypes.JSON'> (Background on this error at: http://sqlalche.me/e/13/l7de)
```

**Comment by hsheth2** [comment]
Yes this does look like a separate issue. Might be related to the JSON type - what does your BigQuery schema look like?

**Comment by user5651** [comment]
Similar to the standard GCP usage tables:
```
[{'mode': 'NULLABLE', 'name': 'logName', 'type': 'STRING'},
 {'fields': [{'mode': 'NULLABLE', 'name': 'type', 'type': 'STRING'},
             {'fields': [{'mode': 'NULLABLE',
                          'name': 'service',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'method',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'project_id',
                          'type': 'STRING'}],
              'mode': 'NULLABLE',
              'name': 'labels',
              'type': 'RECORD'}],
  'mode': 'NULLABLE',
  'name': 'resource',
  'type': 'RECORD'},
 {'fields': [{'mode': 'NULLABLE', 'name': 'serviceName', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'methodName', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'resourceName', 'type': 'STRING'},
             {'fields': [{'mode': 'REPEATED',
                          'name': 'currentLocations',
                          'type': 'STRING'},
                         {'mode': 'REPEATED',
                          'name': 'originalLocations',
                          'type': 'STRING'}],
              'mode': 'NULLABLE',
              'name': 'resourceLocation',
              'type': 'RECORD'},
             {'mode': 'NULLABLE',
              'name': 'numResponseItems',
              'type': 'INTEGER'},
             {'fields': [{'mode': 'NULLABLE',
                          'name': 'code',
                          'type': 'INTEGER'},
                         {'mode': 'NULLABLE',
                          'name': 'message',
                          'type': 'STRING'}],
              'mode': 'NULLABLE',
              'name': 'status',
              'type': 'RECORD'},
             {'fields': [{'mode': 'NULLABLE',
                          'name': 'principalEmail',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'authoritySelector',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'serviceAccountKeyName',
                          'type': 'STRING'},
                         {'fields': [{'mode': 'NULLABLE',
                                      'name': 'principalSubject',
                                      'type': 'STRING'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'principalEmail',
                                                  'type': 'STRING'}],
                                      'mode': 'NULLABLE',
                                      'name': 'firstPartyPrincipal',
                                      'type': 'RECORD'}],
                          'mode': 'REPEATED',
                          'name': 'serviceAccountDelegationInfo',
                          'type': 'RECORD'},
                         {'mode': 'NULLABLE',
                          'name': 'principalSubject',
                          'type': 'STRING'}],
              'mode': 'NULLABLE',
              'name': 'authenticationInfo',
              'type': 'RECORD'},
             {'fields': [{'mode': 'NULLABLE',
                          'name': 'resource',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'permission',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'granted',
                          'type': 'BOOLEAN'},
                         {'fields': [{'mode': 'NULLABLE',
                                      'name': 'service',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'name',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'type',
                                      'type': 'STRING'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'key',
                                                  'type': 'STRING'},
                                                 {'mode': 'NULLABLE',
                                                  'name': 'value',
                                                  'type': 'STRING'}],
                                      'mode': 'REPEATED',
                                      'name': 'labels',
                                      'type': 'RECORD'},
                                     {'mode': 'NULLABLE',
                                      'name': 'uid',
                                      'type': 'STRING'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'key',
                                                  'type': 'STRING'},
                                                 {'mode': 'NULLABLE',
                                                  'name': 'value',
                                                  'type': 'STRING'}],
                                      'mode': 'REPEATED',
                                      'name': 'annotations',
                                      'type': 'RECORD'},
                                     {'mode': 'NULLABLE',
                                      'name': 'displayName',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'createTime',
                                      'type': 'TIMESTAMP'},
                                     {'mode': 'NULLABLE',
                                      'name': 'updateTime',
                                      'type': 'TIMESTAMP'},
                                     {'mode': 'NULLABLE',
                                      'name': 'deleteTime',
                                      'type': 'TIMESTAMP'},
                                     {'mode': 'NULLABLE',
                                      'name': 'etag',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'location',
                                      'type': 'STRING'}],
                          'mode': 'NULLABLE',
                          'name': 'resourceAttributes',
                          'type': 'RECORD'}],
              'mode': 'REPEATED',
              'name': 'authorizationInfo',
              'type': 'RECORD'},
             {'fields': [{'mode': 'NULLABLE',
                          'name': 'callerIp',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'callerSuppliedUserAgent',
                          'type': 'STRING'},
                         {'mode': 'NULLABLE',
                          'name': 'callerNetwork',
                          'type': 'STRING'},
                         {'fields': [{'mode': 'NULLABLE',
                                      'name': 'id',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'method',
                                      'type': 'STRING'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'key',
                                                  'type': 'STRING'},
                                                 {'mode': 'NULLABLE',
                                                  'name': 'value',
                                                  'type': 'STRING'}],
                                      'mode': 'REPEATED',
                                      'name': 'headers',
                                      'type': 'RECORD'},
                                     {'mode': 'NULLABLE',
                                      'name': 'path',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'host',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'scheme',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'query',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'time',
                                      'type': 'TIMESTAMP'},
                                     {'mode': 'NULLABLE',
                                      'name': 'size',
                                      'type': 'INTEGER'},
                                     {'mode': 'NULLABLE',
                                      'name': 'protocol',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'reason',
                                      'type': 'STRING'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'principal',
                                                  'type': 'STRING'},
                                                 {'mode': 'REPEATED',
                                                  'name': 'audiences',
                                                  'type': 'STRING'},
                                                 {'mode': 'NULLABLE',
                                                  'name': 'presenter',
                                                  'type': 'STRING'},
                                                 {'mode': 'REPEATED',
                                                  'name': 'accessLevels',
                                                  'type': 'STRING'}],
                                      'mode': 'NULLABLE',
                                      'name': 'auth',
                                      'type': 'RECORD'}],
                          'mode': 'NULLABLE',
                          'name': 'requestAttributes',
                          'type': 'RECORD'},
                         {'fields': [{'mode': 'NULLABLE',
                                      'name': 'ip',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'port',
                                      'type': 'INTEGER'},
                                     {'fields': [{'mode': 'NULLABLE',
                                                  'name': 'key',
                                                  'type': 'STRING'},
                                                 {'mode': 'NULLABLE',
                                                  'name': 'value',
                                                  'type': 'STRING'}],
                                      'mode': 'REPEATED',
                                      'name': 'labels',
                                      'type': 'RECORD'},
                                     {'mode': 'NULLABLE',
                                      'name': 'principal',
                                      'type': 'STRING'},
                                     {'mode': 'NULLABLE',
                                      'name': 'regionCode',
                                      'type': 'STRING'}],
                          'mode': 'NULLABLE',
                          'name': 'destinationAttributes',
                          'type': 'RECORD'}],
              'mode': 'NULLABLE',
              'name': 'requestMetadata',
              'type': 'RECORD'},
             {'mode': 'NULLABLE', 'name': 'requestJson', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'responseJson', 'type': 'STRING'}],
  'mode': 'NULLABLE',
  'name': 'protopayload_auditlog',
  'type': 'RECORD'},
 {'mode': 'NULLABLE', 'name': 'textPayload', 'type': 'STRING'},
 {'mode': 'NULLABLE', 'name': 'timestamp', 'type': 'TIMESTAMP'},
 {'mode': 'NULLABLE', 'name': 'receiveTimestamp', 'type': 'TIMESTAMP'},
 {'mode': 'NULLABLE', 'name': 'severity', 'type': 'STRING'},
 {'mode': 'NULLABLE', 'name': 'insertId', 'type': 'STRING'},
 {'fields': [{'mode': 'NULLABLE', 'name': 'requestMethod', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'requestUrl', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'requestSize', 'type': 'INTEGER'},
             {'mode': 'NULLABLE', 'name': 'status', 'type': 'INTEGER'},
             {'mode': 'NULLABLE', 'name': 'responseSize', 'type': 'INTEGER'},
             {'mode': 'NULLABLE', 'name': 'userAgent', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'remoteIp', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'serverIp', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'referer', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'cacheLookup', 'type': 'BOOLEAN'},
             {'mode': 'NULLABLE', 'name': 'cacheHit', 'type': 'BOOLEAN'},
             {'mode': 'NULLABLE',
              'name': 'cacheValidatedWithOriginServer',
              'type': 'BOOLEAN'},
             {'mode': 'NULLABLE', 'name': 'cacheFillBytes', 'type': 'INTEGER'},
             {'mode': 'NULLABLE', 'name': 'protocol', 'type': 'STRING'}],
  'mode': 'NULLABLE',
  'name': 'httpRequest',
  'type': 'RECORD'},
 {'fields': [{'mode': 'NULLABLE', 'name': 'id', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'producer', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'first', 'type': 'BOOLEAN'},
             {'mode': 'NULLABLE', 'name': 'last', 'type': 'BOOLEAN'}],
  'mode': 'NULLABLE',
  'name': 'operation',
  'type': 'RECORD'},
 {'mode': 'NULLABLE', 'name': 'trace', 'type': 'STRING'},
 {'mode': 'NULLABLE', 'name': 'spanId', 'type': 'STRING'},
 {'mode': 'NULLABLE', 'name': 'traceSampled', 'type': 'BOOLEAN'},
 {'fields': [{'mode': 'NULLABLE', 'name': 'file', 'type': 'STRING'},
             {'mode': 'NULLABLE', 'name': 'line', 'type': 'INTEGER'},
             {'mode': 'NULLABLE', 'name': 'function', 'type': 'STRING'}],
  'mode': 'NULLABLE',
  'name': 'sourceLocation',
  'type': 'RECORD'}]
```

**Comment by hsheth2** [comment]
@user5651 thanks for sending that along. I just pushed an tiny update to that branch which should fix it. 

Can you try running `git pull` and then retry the ingestion?

**Comment by user5651** [comment]
@hsheth2 Nice! Confirming your fix works. Thanks for all the help on this!
