### ISSUE TITLE
build datahub failed

### ISSUE THREAD

**Issue by liqi444** [linkedin/datahub#2299]
hi everyone
i got build failed when i run ./gradlew build in idea terminal 
i donot know why

18:15:10: Executing task 'build'...

Configuration on demand is an incubating feature.
> Task :li-utils:generateAvroSchema SKIPPED

> Task :li-utils:generateDataTemplate
There are 21 data schema input files. Using input root folder: D:\workspace\datahub-master\li-utils\src\main\pegasus
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 197: D:\workspace\datahub-master\gradle\caches\modules-2\files-2.1\com.linkedin.datahub-gma\core-models-data-template\0.2.49\4e7c1b1eb6d52ba875349e75f080c86d91499074\core-models-data-template-0.2.49.jar:pegasus/com/linkedin/common/AuditStamp.pdl
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.linkedin.pegasus.generator.JavaCodeUtil.annotate(JavaCodeUtil.java:89)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.populateClassContent(JavaDataTemplateGenerator.java:1052)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.generate(JavaDataTemplateGenerator.java:265)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.generatePathSpecMethodsForRecord(JavaDataTemplateGenerator.java:744)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.generateRecord(JavaDataTemplateGenerator.java:668)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.populateClassContent(JavaDataTemplateGenerator.java:1072)
	at com.linkedin.pegasus.generator.JavaDataTemplateGenerator.generate(JavaDataTemplateGenerator.java:265)
	at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.run(PegasusDataTemplateGenerator.java:137)
	at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.main(PegasusDataTemplateGenerator.java:109)

> Task :li-utils:generateDataTemplate FAILED
1 actionable task: 1 executed

**Comment by shirshanka** [comment]
Hi @liqi444 unfortunately DataHub does not build on windows. You would have to use a Linux environment such as [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to build it.

**Comment by liqi444** [comment]
> 
> 
> Hi @liqi444 unfortunately DataHub does not build on windows. You would have to use a Linux environment such as [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) to build it.

thank you !
