### ISSUE TITLE
Can't search any datasets at front page

### ISSUE THREAD

**Issue by luojq661** [linkedin/datahub#2355]
Hi All:
   I follow the quick start and start up the application successfully. When ingest my own data through ingestion framework, I got some error log about elasticsearch, but mysql ingest successfully. And there is no data to show on the front page.
I have no clue about this and need your help.

Here id the elasticsearch error log
```
datahub-mae-consumer      | 07:28:26.404 [I/O dispatcher 1] WARN  org.elasticsearch.client.RestClient - request [POST http://elasticsearch:9200/_bulk?timeout=1m] returned 1 warnings: [299 Elasticsearch-7.9.3-c4138e51121ef06a6404866cddc601906fe5c868 "[types removal] Specifying types in bulk requests is deprecated."]
datahub-mae-consumer      | 07:28:26.406 [I/O dispatcher 1] INFO  c.l.m.u.e.ElasticsearchConnector - Error feeding bulk request. No retries left
datahub-mae-consumer      | org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]]
datahub-mae-consumer      | 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:526)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:502)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestHighLevelClient$1.onFailure(RestHighLevelClient.java:477)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:605)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:362)
datahub-mae-consumer      | 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:343)
datahub-mae-consumer      | 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
datahub-mae-consumer      | 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
datahub-mae-consumer      | 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
datahub-mae-consumer      | 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
datahub-mae-consumer      | 	at java.lang.Thread.run(Thread.java:748)
datahub-mae-consumer      | 	Suppressed: org.elasticsearch.client.ResponseException: POST http://elasticsearch:9200/_bulk?timeout=1m: HTTP/1.1 400 Bad Request
datahub-mae-consumer      | {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_retry_on_conflict]"},"status":400}
datahub-mae-consumer      | 		at org.elasticsearch.client.RestClient$1.completed(RestClient.java:354)
datahub-mae-consumer      | 		... 16 common frames omitted
```

Data has been loaded into MySQL 
```
mysql> select count(*) from metadata_aspect;
+----------+
| count(*) |
+----------+
|      472 |
+----------+
1 row in set (0.05 sec)
```

But no data in `metadata_index`
```
mysql> select count(*) from metadata_index;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)
```

Indices created in Elasticsearch
```
green  open .kibana-event-log-7.9.3-000001 wLGjotkXQeGMg7W7eczpxg 1 0 1  0  5.5kb  5.5kb
yellow open dashboarddocument              ScnJCgJQQIqOVeq6Y_9_sQ 1 1 0  0   208b   208b
green  open .apm-agent-configuration       K0gBkpryS0iJ7liJYY4vKQ 1 0 0  0   208b   208b
yellow open datajobdocument                sFGBwwe7QkC7w9WNGe_Bjw 1 1 0  0   208b   208b
yellow open chartdocument                  uyXSbQfjT6-OjP25G5BpoQ 1 1 0  0   208b   208b
yellow open dataprocessdocument            c3grGbsLSyOZgqtFlgvB5Q 1 1 0  0   208b   208b
green  open .kibana_1                      CruFtQyQS5CJQHu43mI2_A 1 0 9  0 10.4mb 10.4mb
yellow open tagdocument                    Mfd60oPUShajzMatu3j3CA 1 1 0  0   208b   208b
yellow open datasetdocument                YQw2Jx9OQbunzfpe4PkG8A 1 1 0  0   208b   208b
green  open .apm-custom-link               WGc_QpHvS8OL2VI0ZHncXQ 1 0 0  0   208b   208b
green  open .kibana_task_manager_1         IoTgHmgJQAyR2xdBKkQ5Dw 1 0 6 93   70kb   70kb
yellow open dataflowdocument               dDn4cLAGT-uFSVnfaOoe0Q 1 1 0  0   208b   208b
yellow open mlmodeldocument                gmkmXJ2xTtOwXvq8lWNcbg 1 1 0  0   208b   208b
yellow open corpuserinfodocument           iKSZ-9qOSQGXKsJ4hiCoSg 1 1 0  0   208b   208b
```

![image](https://user-images.githubusercontent.com/22184660/113831982-c1703680-97ba-11eb-9d4e-5eb147283028.png)

**Comment by shirshanka** [comment]
@luojq661 : Your elasticsearch indexes are probably unhealthy. 
https://datahubproject.io/docs/debugging#how-can-i-confirm-if-all-docker-containers-are-running-as-expected-after-a-quickstart
Can you run `datahub check local-docker` and post your result here?

**Comment by luojq661** [comment]
@shirshanka : Thank you for your reply.
There is result after run `datahub check local-docker`

```
Everest:datahub tiger$ datahub check local-docker
✔ No issues detected
```

What else you need, please let me know.

**Comment by luojq661** [comment]
I found the reason, RAM is set too small
