### ISSUE TITLE
Issue with running acryl-datahub

### ISSUE THREAD

**Issue by iremi** [linkedin/datahub#2375]
After setting up Datahub with a docker and having it run normally, I'm having issues with setting up the python package acryl-datahub.
I successfully install it with pip but after running `datahub` and `python -m datahub` I get the error 
`No module named datahub.__main__; 'datahub' is a package and cannot be directly executed`

I also tried installing it through a venv [with these instructions](https://pypi.org/project/acryl-datahub/0.0.3/) with the same result.

Is it possible the run it in a different way or is there an issue with my installation?

Environment:
Operating System: Windows 10
Python Version Used: Python 3.8 
acryl-datahub Version Used: 0.0.4

**Comment by hsheth2** [comment]
Hi @iremi - thanks for reporting this! The PR (#2359) that added support for that just got merged the other day, and we hadn't published a new version to PyPI.

I've gone ahead on published a new version manually, so it should start working after you update by running `python -m pip install --upgrade acryl-datahub`. Let me know if you have any further issues 🙂

**Comment by iremi** [comment]
Thank you for the quick response. I'll check and close the issue once I can check on the target system.

**Comment by iremi** [comment]
After upgrading to v0.1.0 and running python3 -m datahub version I get the following error:

Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python\lib\site-packages\datahub\__main__.py", line 1, in <module>
    from datahub.entrypoints import datahub
  File "C:\Python\lib\site-packages\datahub\entrypoints.py", line 10, in <module>
    from datahub.check.check_cli import check
  File "C:\Python\lib\site-packages\datahub\check\check_cli.py", line 7, in <module>
    from datahub.check.json_file import check_mce_file
  File "C:\Python\lib\site-packages\datahub\check\json_file.py", line 1, in <module>
    from datahub.ingestion.source.mce_file import MetadataFileSource
  File "C:\Python\lib\site-packages\datahub\ingestion\source\mce_file.py", line 7, in <module>
    from datahub.ingestion.source.metadata_common import MetadataWorkUnit
  File "C:\Python\lib\site-packages\datahub\ingestion\source\metadata_common.py", line 4, in <module>
    from datahub.metadata.com.linkedin.pegasus2avro.mxe import MetadataChangeEvent
  File "C:\Python\lib\site-packages\datahub\metadata\__init__.py", line 3, in <module>
    from .schema_classes import SCHEMA as get_schema_type
  File "C:\Python\lib\site-packages\datahub\metadata\schema_classes.py", line 8, in <module>
    from avrogen.dict_wrapper import DictWrapper
  File "C:\Python\lib\site-packages\avrogen\__init__.py", line 1, in <module>
    from .schema import generate_schema,  write_schema_files
  File "C:\Python\lib\site-packages\avrogen\schema.py", line 12, in <module>
    from .core_writer import generate_namespace_modules, clean_fullname
  File "C:\Python\lib\site-packages\avrogen\core_writer.py", line 5, in <module>
    from . import logical
  File "C:\Python\lib\site-packages\avrogen\logical.py", line 23, in <module>
    EPOCH_TT = -datetime.datetime(1970, 1, 1).astimezone(tzlocal.get_localzone()).utcoffset().total_seconds()
OSError: [Errno 22] Invalid argument

I have datahub successfully running in the background on docker.

**Comment by hsheth2** [comment]
Really interesting - seems like a bug in Python on windows: https://bugs.python.org/issue36759.

I'll try to figure out a solution or workaround.

**Comment by iremi** [comment]
I made the change outlined in [#2403](https://github.com/linkedin/datahub/pull/2403) and can now run the datahub command!
Thank you for your help.

**Comment by hsheth2** [comment]
Awesome!

**Comment by iremi** [comment]
I have bad news. After making the changes ([#2403](https://github.com/linkedin/datahub/pull/2403)) I can indeed get the datahub command working but **DataHub on http://localhost:9002 becomes unreachable.** 

I nuked my entire datahub docker containers, set everything up again and confirmed that it was reachable until changing the logical.py. After the change and restarting the Datahub docker containers I can no longer access Datahub.
