### ISSUE TITLE
Unable to parse an avro schema for Kafka 

### ISSUE THREAD

**Issue by youngwookim** [linkedin/datahub#2565]
**Describe the bug**

Got a traceback from my ingestion job that is gathering meta data from kafka and schema registry:
```
Traceback (most recent call last):
  File "/usr/local/bin/datahub", line 8, in <module>
    sys.exit(datahub())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/datahub/entrypoints.py", line 74, in ingest
    pipeline.run()
  File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/run/pipeline.py", line 108, in run
    for wu in self.source.get_workunits():
  File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/source/kafka.py", line 79, in get_workunits
    mce = self._extract_record(t)
  File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/source/kafka.py", line 112, in _extract_record
    fields = schema_util.avro_schema_to_mce_fields(schema.schema_str)
  File "/usr/local/lib/python3.8/site-packages/datahub/ingestion/extractor/schema_util.py", line 117, in avro_schema_to_mce_fields
    parsed_schema: avro.schema.Schema = schema_parse_fn(avro_schema_string)
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 1244, in parse
    return SchemaFromJSONData(json_data, names)
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 1215, in SchemaFromJSONData
    return parser(json_data, names=names)
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 1136, in _SchemaFromJSONObject
    return RecordSchema(
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 1003, in __init__
    super(RecordSchema, self).__init__(
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 440, in __init__
    names.Register(self)
  File "/usr/local/lib/python3.8/site-packages/avro/schema.py", line 399, in Register
    raise SchemaParseException(
avro.schema.SchemaParseException: record is a reserved type name.

```

**To Reproduce**

This is my avro schema on schema registry:
```
{
  "type": "record",
  "name": "record",
  "fields": [
    {
      "name": "dt",
      "type": [
        "null",
        {
          "type": "int",
          "logicalType": "date"
        }
      ],
      "default": null
    },
    {
      "name": "value",
      "type": [
        "null",
        "string"
      ],
      "default": null
    }
  ]
}
```
Actually, the schema was generated by Apache Flink. See https://ci.apache.org/projects/flink/flink-docs-release-1.13/docs/connectors/table/formats/avro-confluent/

**Additional context**

I'm using the latest datahub and my ingestion job is running on k8s with `linkedin/datahub-ingestion:latest` docker image.

**Comment by youngwookim** [comment]
It looks like this line of the schema is a cause of failure:
```
"name": "record",
......
```

`record` is the existing type name of avro's complex type. https://github.com/apache/avro/blob/master/lang/py3/avro/schema.py#L399

**Comment by hsheth2** [comment]
@youngwookim seems like you're right

The current Avro spec (http://avro.apache.org/docs/current/spec.html#names) says:

> Primitive type names have no namespace and their names may not be defined in any namespace.

However, record is not a primitive type and hence it seems like the Python Avro implementation does not follow the spec here. Might be worth opening an issue on their repo.

In the short term, unfortunately it seems the easiest solution would be to rename the record type or put it inside a namespace.

**Comment by youngwookim** [comment]
@hsheth2, That makes sense to me. Thanks for the comment. Will close this and look into the implementation of schema generation.
