### ISSUE TITLE
Dataset urns/names with `/` breaks the UI

### ISSUE THREAD

**Issue by frsann** [linkedin/datahub#2581]
**Describe the bug**
Having `/`in the dataset urn (e.g. in the name part of a S3 blob) breaks the UI. 

**To Reproduce**
1. Ingest a dataset with a URN similar to: `urn:li:dataset:(urn:li:dataPlatform:s3,my_bucket/some/path,PROD)`
2. Go to the web UI
3. click through to the dataset
4. An error appears in the UI, and an error similar to the below is logged in the frontend pod:
```
13:57:18 [Thread-334] WARN  n.g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/browsePaths) : java.lang.RuntimeException: Failed to retrieve browse paths: entity type DATASET, urn urn:li:dataset:(urn:li:dataPlatform:s3,my_bucket
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve browse paths: entity type DATASET, urn urn:li:dataset:(urn:li:dataPlatform:s3,my_bucket
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to retrieve browse paths: entity type DATASET, urn urn:li:dataset:(urn:li:dataPlatform:s3,my_bucket
        at com.linkedin.datahub.graphql.resolvers.browse.BrowsePathsResolver.lambda$get$1(BrowsePathsResolver.java:38)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        ... 1 common frames omitted
Caused by: java.lang.RuntimeException: Failed to retrieve dataset with urn urn:li:dataset:(urn:li:dataPlatform:s3,my_bucket, invalid urn
        at com.linkedin.datahub.graphql.types.dataset.DatasetUtils.getDatasetUrn(DatasetUtils.java:15)
        at com.linkedin.datahub.graphql.types.dataset.DatasetType.browsePaths(DatasetType.java:147)
        at com.linkedin.datahub.graphql.resolvers.browse.BrowsePathsResolver.lambda$get$1(BrowsePathsResolver.java:35)
        ... 2 common frames omitted
```

**Expected behavior**
The dataset should show up in the UI

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.3.1
 - Browser : Safari
 - Version: 0653edc9b573e8283eeb2fce9b49318666235179

**Comment by shirshanka** [comment]
Fixed via #2623 
@frsann please re-open if you are still seeing this. 
@gabe-lyons : FYI
