### ISSUE TITLE
datahub-frontend-react failed to start up

### ISSUE THREAD

**Issue by luojq661** [linkedin/datahub#2621]
datahub-frontend-react failed to start up,  logs as follows:

```
$ docker logs datahub-frontend-react
Oops, cannot start the server.
Configuration error: Configuration error[datahub-frontend/conf/application.conf: 143: Could not resolve substitution to a value: ${KAFKA_BOOTSTRAP_SERVER}]
        at play.api.Configuration$.configError(Configuration.scala:156)
        at play.api.Configuration$.load(Configuration.scala:102)
        at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:86)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:40)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:25)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: com.typesafe.config.ConfigException$UnresolvedSubstitution: datahub-frontend/conf/application.conf: 143: Could not resolve substitution to a value: ${KAFKA_BOOTSTRAP_SERVER}
        at com.typesafe.config.impl.ConfigReference.resolveSubstitutions(ConfigReference.java:111)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.SimpleConfigObject$ResolveModifier.modifyChildMayThrow(SimpleConfigObject.java:379)
        at com.typesafe.config.impl.SimpleConfigObject.modifyMayThrow(SimpleConfigObject.java:312)
        at com.typesafe.config.impl.SimpleConfigObject.resolveSubstitutions(SimpleConfigObject.java:398)
        at com.typesafe.config.impl.ResolveContext.realResolve(ResolveContext.java:179)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:142)
        at com.typesafe.config.impl.ResolveContext.resolve(ResolveContext.java:231)
        at com.typesafe.config.impl.SimpleConfig.resolveWith(SimpleConfig.java:78)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:68)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:63)
        at com.typesafe.config.impl.SimpleConfig.resolve(SimpleConfig.java:41)
        at play.api.Configuration$.load(Configuration.scala:98)
        ... 4 more
```
Does anyone know the reason?

**Comment by jjoyce0510** [comment]
Hi there. Thanks for reporting! Taking a look

**Comment by jjoyce0510** [comment]
@luojq661 How did you attempt to start the container? Using ./quickstart.sh? or something else? 

I recently tried starting up using `docker/quickstart.sh` and it seems to be working. It's likely the case that when you're running the container you are not providing it the required env file. (Located under `docker/datahub-frontend/env/docker.env`

**Comment by luojq661** [comment]
@jjoyce0510 
Thank you for your reply. 
There are missing `docker/datahub-frontend/env/docker.env` indeed and start up successfully.
