### ISSUE TITLE
Users not assigned to app in OIDC receives unhelpful exception

### ISSUE THREAD

**Issue by RickardCardell** [linkedin/datahub#2886]
**Describe the bug**
Precondition: A working datahub installation configured with Okta.
When a user that is not assigned to the Datahub app and enters the Datahub URL, the user is redirected to Okta. The user then authenticates successfully, and is redirected back to Datahub. The user is then shown a rather unhelpful "Oops, an error occurred"-page.

**To Reproduce**
1. Follow Okta setup guide https://github.com/linkedin/datahub/blob/master/docs/how/auth/sso/configure-oidc-react.md
1. Create a user in Okta that is **not** assigned to the Datahub app
1. Enter the Datahub url in a browser
    * You should be redirected to the Okta login page
1. Login with the user that is not assigned to the Datahub app
    * You should be redirected back to Datahub
1.  The "Oops, an error occurred"-page is shown

**Expected behavior**
At minumum: 

- a more helpful error message explaining the issue; that the user has to be assigned the app in Okta before logging in. 
 
Other options: 
- redirect the user to a configurable redirection-url
- show a configurable error message so that the necessary actions can be communicated to the user

**Screenshots**
<img width="752" alt="Screenshot 2021-07-15 at 14 25 28" src="https://user-images.githubusercontent.com/101401/125787751-12074ce7-2dd1-40d4-8bf6-73ca584c562f.png">

final url: `http://localhost:9002/callback/oidc?state=<some_state>&error=access_denied&error_description=User+is+not+assigned+to+the+client+application`.

**Logs**
```
14:26:22 [application-akka.actor.default-dispatcher-10] ERROR o.p.o.c.extractor.OidcExtractor - Bad authentication response, error=access_denied
14:26:22 [application-akka.actor.default-dispatcher-10] ERROR application -

! @7kcibpadc - Internal server error, for (GET) [/callback/oidc?state=sEwhFq0oSvDhAZwNGhKEeAc1xBQQ5NdSdaPPzjqDoJM&error=access_denied&error_description=User+is+not+assigned+to+the+client+application.] ->

play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: Failed to authenticate current user. Cannot find valid identity provider profile in session]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:247)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:176)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:363)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:361)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to authenticate current user. Cannot find valid identity provider profile in session
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	... 6 common frames omitted
Caused by: java.lang.RuntimeException: Failed to authenticate current user. Cannot find valid identity provider profile in session
	at react.auth.AuthModule.handleOidcCallback(AuthModule.java:155)
	at react.auth.AuthModule.access$100(AuthModule.java:36)
	at react.auth.AuthModule$2.perform(AuthModule.java:86)
	at react.auth.AuthModule$2.perform(AuthModule.java:79)
	at org.pac4j.play.CallbackController.lambda$callback$0(CallbackController.java:56)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 7 common frames omitted
```

**Desktop (please complete the following information):**
 - OS: OS agnostic
 - Browser: Browser agnostic
 - Version: On current master and previous to that as well

**Additional context**
I'm not sure if this issue is due to that Okta is not following the OIDC callback flow or not, since it would make sense if an error message is shown directly when the user logs in.
Please enlighten me if that's the case.

What suprises me is that `pac4j` which handles the OIDC integration, doesn't seem to support this case at all for OIDC, since it just logs:
`ERROR o.p.o.c.extractor.OidcExtractor - Bad authentication response, error=access_denied`

**Comment by jjoyce0510** [comment]
Hi @RickardCardell - Agree the user experience here is not ideal.

In my mind, we should provide a basic error page when something like this happens that as you suggest shows the error message we receive from the Identity Provider. 

I would not call this a "bug" per say, because the behavior of not permitting the user to log in is expected, right?

**Comment by RickardCardell** [comment]
> I would not call this a "bug" per say, because the behavior of not permitting the user to log in is expected, right?
 Correct, not a bug in that sense, but perhaps a bug in that the user is clueless about what happened. Maybe it could be called a missing feature as well :)
