### ISSUE TITLE
How to check frontend and gms version

### ISSUE THREAD

**Issue by smartnewsdingli** [linkedin/datahub#2907]
hi all,

I pull latest code and build to run. But I find it has below exception.
My question is:
1. How can I check frontend and gms version?
2. What could be possible reason cause it?

> 07:55:55 [main] INFO  play.api.Play - Application started (Prod)
07:55:56 [main] INFO  play.core.server.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9002
07:56:20 [Thread-5] ERROR EntityClient - ERROR: Your datahub-frontend instance version is ahead of your gms instance. Please update your gms to the latest Datahub release
07:56:20 [Thread-1] INFO  play.core.server.AkkaHttpServer - Stopping server...
07:56:20 [pool-4-thread-1] ERROR c.l.common.callback.CallbackAdapter - Failed to convert callback error, original exception follows:
com.linkedin.r2.message.rest.RestException: Received error 404 from server for URI http://datahub-gms-graphql.data-catalogue.svc.cluster.local:8091/entities
	at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:76)
	at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
07:56:20 [Thread-6] WARN  n.g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/browse) : java.lang.RuntimeException: Failed to execute browse: entity type DATASET, path [], filters: null, start: 0, count: 10
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to execute browse: entity type DATASET, path [], filters: null, start: 0, count: 10
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to execute browse: entity type DATASET, path [], filters: null, start: 0, count: 10
	at com.linkedin.datahub.graphql.resolvers.browse.BrowseResolver.lambda$get$1(BrowseResolver.java:50)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 1 common frames omitted
Caused by: java.lang.ClassCastException: com.linkedin.r2.RemoteInvocationException cannot be cast to com.linkedin.restli.client.RestLiResponseException
	at com.linkedin.entity.client.EntityClient.sendClientRequest(EntityClient.java:69)
	at com.linkedin.entity.client.EntityClient.browse(EntityClient.java:188)
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.browse(DatasetType.java:130)
	at com.linkedin.datahub.graphql.resolvers.browse.BrowseResolver.lambda$get$1(BrowseResolver.java:41)
	... 2 common frames omitted

**Comment by jjoyce0510** [comment]
The best way to check the version is to look at the tag associated with the Docker image that is running.  Each certified release image will come with a tag like v0.8.3 that will detail the version!

**Comment by jjoyce0510** [comment]
@smartnewsdingli Was this able to work for you?

**Comment by smartnewsdingli** [comment]
Yes, it's working. But actually i find i mis-config the backend service. 
The service should be datahub-gms rather than datahub-gms-graphql.
Thank you!

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) with any additional follow-up!
