### ISSUE TITLE
Unique expecting 0 or 1 results but got [2] error after deleting data

### ISSUE THREAD

**Issue by smartnewsdingli** [linkedin/datahub#3101]
I happened to delete all dataset records in metadata_aspect_v2, and then open main UI,  find below error. What could be the root cause of `Unique expecting 0 or 1 results but got [2]`? I have delete all data so the result should always 0, is this correct?

> 06:45:34 [Thread-18] WARN  n.g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/search/searchResults[0]/entity) : java.lang.RuntimeException: Failed to retrieve entities of type Dataset
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
	at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$70(GmsGraphQLEngine.java:529)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 1 common frames omitted
Caused by: java.lang.RuntimeException: Failed to batch load Datasets
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:96)
	at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$70(GmsGraphQLEngine.java:527)
	... 2 common frames omitted
Caused by: com.linkedin.restli.client.RestLiResponseException: com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: javax.persistence.NonUniqueResultException: **Unique expecting 0 or 1 results but got [2]**
	at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:130)
	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponse(ResponseFutureImpl.java:94)
	at com.linkedin.entity.client.EntityClient.sendClientRequest(EntityClient.java:67)
	at com.linkedin.entity.client.EntityClient.batchGet(EntityClient.java:105)
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:82)
	... 3 common frames omitted

**Comment by smartnewsdingli** [comment]
I find the root cause, I create two datahub DBs (one for production and one for dev) in one RDS instance. and this [check](https://github.com/linkedin/datahub/blob/f40bf1ce19b00c89beef76d5b52b4ed3108aa0f0/metadata-io/src/main/java/com/linkedin/metadata/entity/AspectStorageValidationUtil.java#L25) raise the error.
But to be honesty, this error message is misleading, and do we need this validation really?

**Comment by maggiehays** [comment]
Hello, this issue has been open for more than 3 months without activity. We will close it out for now, but please feel free to follow up with us in [DataHub Slack](slack.datahubproject.io) if you are looking for additional support!
