### ISSUE TITLE
Cannot run GMS v0.8.10 on Confluent Cloud with ACLs: java.lang.IllegalStateException

### ISSUE THREAD

**Issue by dingobar** [linkedin/datahub#3111]
**Describe the bug**

I cannot get GMS to run in v0.8.10, as it throws the exception below. It works just fine when using the kafka setup job on a local dockerized kafka cluster, but when using Confluent Cloud it seems there is some issue with the Group ID. It may be related to this issue: https://github.com/spring-projects/spring-kafka/issues/236 .

There are ACLs in the cluster that ensure that only certain groups can read/write to certain topics. Below, I've added the custom topic names and custom group ID (as you can see, they are prefixed with the same word).

Do you have any idea what the issue could be here? I'm a bit stuck to be honest, and I don't know enough about spring to really understand the stack trace.

```
10:03:42.470 [main] ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.IllegalStateException: Another endpoint is already registered with id 'datadelivery-gexyo.datahub-dev'
        at org.springframework.util.Assert.state(Assert.java:73)
        at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:170)
        at org.springframework.kafka.config.KafkaListenerEndpointRegistry.registerListenerContainer(KafkaListenerEndpointRegistry.java:146)
        at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.registerAllEndpoints(KafkaListenerEndpointRegistrar.java:164)
        at org.springframework.kafka.config.KafkaListenerEndpointRegistrar.afterPropertiesSet(KafkaListenerEndpointRegistrar.java:158)
        at org.springframework.kafka.annotation.KafkaListenerAnnotationBeanPostProcessor.afterSingletonsInstantiated(KafkaListenerAnnotationBeanPostProcessor.java:263)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:896)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:921)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:554)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:888)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:357)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1443)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1407)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:821)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:407)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
        at org.eclipse.jetty.server.Server.doStart(Server.java:371)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
        at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
2021-08-19 10:03:42.470:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@3339ad8e{Open source GMS,/,file:///tmp/jetty-0_0_0_0-8080-war_war-_-any-5403685138894384792.dir/webapp/,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
```

The configuration for GMS in `values.yaml` looks like this:

```
datahub-gms:
  enabled: true
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  extraEnvs:
    # All Secret
    # Some of these are not needed, not clear which
    # See https://datahubproject.io/docs/how/kafka-config
    - name: METADATA_CHANGE_EVENT_NAME
      value: "pub.datacatalogue-agpnj.metadatachangeevent-v4"
    - name: METADATA_AUDIT_EVENT_NAME
      value: "pub.datadelivery-gexyo.metadataauditevent-v4"
    - name: FAILED_METADATA_CHANGE_EVENT_NAME
      value: "pub.datadelivery-gexyo.failedmetadatachangeevent"
    - name: KAFKA_MCE_TOPIC_NAME
      value: "pub.datacatalogue-agpnj.metadatachangeevent-v4"
    - name: KAFKA_FMCE_TOPIC_NAME
      value: "pub.datadelivery-gexyo.failedmetadatachangeevent"
    - name: KAFKA_TOPIC_NAME
      value: "pub.datadelivery-gexyo.metadataauditevent-v4"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "datadelivery-gexyo.dfds-datahub"
```

**Comment by dingobar** [comment]
Closing this because I no longer think this has anything to do with ACLs, but rather the setting itself being broken (potentially).
