### ISSUE TITLE
Error importing a Superset chart with an empty metric label

### ISSUE THREAD

**Issue by cccs-eric** [linkedin/datahub#3792]
**Describe the bug**
While importing Superset dashboards, I ran into some occurrences where a metric  would have an empty `label` string.  Here is the chart data as returned by the Superset API:
```json
{
    "adhoc_filters": [],
    "bottom_margin": "auto",
    "color_scheme": "supersetColors",
    "columns": [],
    "datasource": "242__table",
    "extra_form_data": {},
    "granularity_sqla": "date",
    "groupby": [
        "type"
    ],
    "label_colors": {},
    "metrics": [
        {
            "aggregate": "SUM",
            "column": {
                "business_type": null,
                "column_name": "COUNT",
                "description": null,
                "expression": null,
                "filterable": true,
                "groupby": true,
                "id": 3772,
                "is_dttm": false,
                "python_date_format": null,
                "type": "LONGLONG",
                "type_generic": 0,
                "verbose_name": null
            },
            "expressionType": "SIMPLE",
            "hasCustomLabel": false,
            "isNew": false,
            "label": "",
            "optionName": "metric_b55n1d75khf_9fzxgcbt5ro",
            "sqlExpression": null
        }
    ],
    "order_desc": true,
    "row_limit": 100,
    "slice_id": 129,
    "time_range": "No filter",
    "time_range_endpoints": [
        "inclusive",
        "exclusive"
    ],
    "url_params": {},
    "viz_type": "dist_bar",
    "x_ticks_layout": "auto",
    "y_axis_bounds": [
        null,
        null
    ],
    "y_axis_format": "SMART_NUMBER"
}
```
As you can see, the `label` attribute is empty:
```json
            "isNew": false,
            "label": "",
            "optionName": "metric_b55n1d75khf_9fzxgcbt5ro",
```

When ingesting, I get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/.vscode-server/extensions/ms-python.python-2021.12.1559732655/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/usr/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "metadata-ingestion/test.py", line 40, in <module>
    pipeline.run()
  File "/home/git/datahub/metadata-ingestion/src/datahub/ingestion/run/pipeline.py", line 153, in run
    for wu in itertools.islice(
  File "/home/git/datahub/metadata-ingestion/src/datahub/ingestion/source/superset.py", line 323, in get_workunits
    yield from self.emit_chart_mces()
  File "/home/git/datahub/metadata-ingestion/src/datahub/ingestion/source/superset.py", line 313, in emit_chart_mces
    chart_snapshot = self.construct_chart_from_chart_data(chart_data)
  File "/home/git/datahub/metadata-ingestion/src/datahub/ingestion/source/superset.py", line 281, in construct_chart_from_chart_data
    "Metrics": ", ".join(metrics),
TypeError: sequence item 0: expected str instance, NoneType found
```

**Expected behavior**
I think the [get_metric_name()](https://github.com/linkedin/datahub/blob/21fbfbba085d06d513445f5e7177306c089efb41/metadata-ingestion/src/datahub/ingestion/source/superset.py#L67) should return `""` in this case.

**Comment by cccs-eric** [comment]
PR to follow shortly.

**Comment by maggiehays** [comment]
Thanks for pushing a fix for this, @cccs-eric! We'll close out this issue for now.
