### ISSUE TITLE
Unable to run quickstart: - Docker doesn't seem to be running. Did you start it?

### ISSUE THREAD

**Issue by pavanmallepudi** [linkedin/datahub#4225]
I am trying to install datahub using quick start on windows using docker desktop .

all docker commands are running in command prompt like below
docker ps 

but while running datahub 

python3 -m datahub docker quickstart

its prompting as below 

Unable to run quickstart:
- Docker doesn't seem to be running. Did you start it?

**Comment by anshbansal** [comment]
Can you run these commands one-by-one and share the output?

First
```
python -c "import platform; print(platform.platform())"
```

Second
```
python3 -c "import sys; print(sys.version); print(sys.executable); import datahub; print(datahub.__file__); print(datahub.__version__);"
```

Third
```
python3 -c "import docker; print(f'{docker.from_env()}')"
```

**Comment by pavanmallepudi** [comment]
First

python -c "import platform; print(platform.platform())"
Windows-10-10.0.19041-SP0

Second 

python3 -c "import sys; print(sys.version); print(sys.executable); import datahub; print(datahub.__file__); print(datahub.__version__);"
3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 16:30:00) [MSC v.1900 64 bit (AMD64)]
C:\Users\DataSpaceUser\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\python.exe
C:\Users\DataSpaceUser\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\datahub\__init__.py
0.8.26.8


Third

python3 -c "import docker; print(f'{docker.from_env()}')"

self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

-packages\Python37\site-packages\docker\api\client.py", line 165, in __init__
    'Install pypiwin32 package to enable npipe:// support'
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support

**Comment by anshbansal** [comment]
Can you try running this command

```
python3 -m pip install pypiwin32
```

and then try to run the quickstart command again? If it does not work then please send the output of the third command again.

**Comment by pavanmallepudi** [comment]
Hye I am using 3.7 uninstalling it and upgrading python 3.10 worked for m

**Comment by anshbansal** [comment]
The maximum Python version we have tested this with is `3.9.9`. Any version above that we would not recommend using currently as the automated tests have not run for those versions. 

Was there a particular reason you tried upgrading your python version instead of installing the python package?

**Comment by pavanmallepudi** [comment]
I tried installing it 

python3 -m pip install pypiwin32


still faced same issue so tried upgrading python and it worked for me

**Comment by pavanmallepudi** [comment]
Thanks for your quick response .

**Comment by asd51731** [comment]
hi, i meet the same problem, but the third step is not the same, here is my response:
(datahub) [root@izbp1jfnhj3x2mwmhsbh70z venv]# python  -c "import platform; print(platform.platform())"
Linux-3.10.0-693.2.2.el7.x86_64-x86_64-with-centos-7.4.1708-Core
(datahub) [root@izbp1jfnhj3x2mwmhsbh70z venv]# python -c "import sys; print(sys.version); print(sys.executable); import datahub; print(datahub.__file__); print(datahub.__version__);"
3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
/mnt/zxx/datahub/venv/datahub/bin/python
/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/datahub/__init__.py
0.8.27
(datahub) [root@izbp1jfnhj3x2mwmhsbh70z venv]# python -c "import docker; print(f'{docker.from_env()}')"
Traceback (most recent call last):
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/client.py", line 101, in from_env
    **kwargs_from_env(**kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/mnt/zxx/datahub/venv/datahub/lib64/python3.6/site-packages/docker/api/client.py", line 222, in _retrieve_server_version
    f'Error while fetching server API version: {e}'
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

Can you give me some help please.

**Comment by anshbansal** [comment]
Is docker actually running for you @asd51731? 

Check using 
`docker ps -a`

**Comment by asd51731** [comment]
> docker ps -a

(datahub) [root@izbp1jfnhj3x2mwmhsbh70z venv]# docker ps -a
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by anshbansal** [comment]
you need to install and start docker for this to work. A quick search should give you the required docs.

**Comment by asd51731** [comment]
> you need to install and start docker for this to work. A quick search should give you the required docs.
yes , I restart docker it works, thanks!

**Comment by IanHopkinson** [comment]
> I tried installing it
> 
> python3 -m pip install pypiwin32
> 
> still faced same issue so tried upgrading python and it worked for me.
> 
> Can you please help me with 4229 tooo

There is a postinstall step for pypiwin32, you need to run:

python <path-to-python-env>\Scripts\pywin32_postinstall.py -install

This works for me, I get a fail following just the pip install which is resolved on running postinstall. It will be a Windows only issue.

Reference:
https://github.com/twosixlabs/armory/issues/156

**Comment by maggiecandyland** [comment]
I tried to start datahub at linux via "datahub docker quickstart". I got error:

_Unable to run quickstart:
- Docker doesn't seem to be running. Did you start it?

I start docker engine  as :  sudo service docker start
There is no error message for starting docker engine. 
My python version is 3.8.10

Any hint? 
Thanks.

**Comment by dilippulimi** [comment]
Hi, I have got the same problem.

# datahub docker quickstart
Unable to run quickstart:
- Docker doesn't seem to be running. Did you start it?
# python3 -c "import platform; print(platform.platform())"
Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
# python3 -c "import sys; print(sys.version); print(sys.executable); import datahub; print(datahub.__file__); print(datahub.__version__);"
3.10.5 (main, Jul 12 2022, 11:32:11) [GCC 10.2.1 20210110]
/usr/local/bin/python3
/usr/local/lib/python3.10/site-packages/datahub/__init__.py
0.8.41.2
# python3 -c "import docker; print(f'{docker.from_env()}')"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "/usr/local/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "/usr/local/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 96, in from_env
    return cls(
  File "/usr/local/lib/python3.10/site-packages/docker/client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "/usr/local/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Please help me on this.

Thanks,
Dilip

**Comment by anshbansal** [comment]
For any further questions please use https://slack.datahubproject.io/ as we don't know whether all of these are same problems or different problems.
