### ISSUE TITLE
Cannot Relaunch datahub-gms - javax.servlet.UnavailableException: Servlet Not Initialized

### ISSUE THREAD

**Issue by eeepmb** [linkedin/datahub#4234]
Hi there, 
I just tried to activate authentication for DataHub and struggling to relaunch `datahub-gms`.

I followed [this instruction](https://datahubproject.io/docs/docker/development/#running-a-specific-service) to relaunch it but it lead me into #3690. Running `DOCKER_BUILDKIT=1 docker-compose -p datahub -f docker-compose.yml -f docker-compose.override.yml up datahub-gms` leads me to #1759 although I am not using Kubernetes or Helm. All containers are running on one instance (AWS EC2 Linux/x86_64) and no connection details of MySQL were changed.

```
datahub-gms               | 16:24:43.469 [main] WARN  o.s.w.c.s.XmlWebApplicationContext:558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.linkedin.gms.factory.common.GitVersionFactory]; nested exception is java.io.FileNotFoundException: class path resource [git.properties] cannot be opened because it does not exist
datahub-gms               | 16:24:43.489 [main] ERROR o.s.web.context.ContextLoader:313 - Context initialization failed
datahub-gms               | org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.linkedin.gms.factory.common.GitVersionFactory]; nested exception is java.io.FileNotFoundException: class path resource [git.properties] cannot be opened because it does not exist
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
datahub-gms               | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:921)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:554)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:888)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:357)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1443)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1407)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:821)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
datahub-gms               | Caused by: java.io.FileNotFoundException: class path resource [git.properties] cannot be opened because it does not exist
datahub-gms               | 	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
datahub-gms               | 	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:159)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:99)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:73)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:59)
datahub-gms               | 	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:67)
datahub-gms               | 	at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:37)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:455)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:274)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170)
datahub-gms               | 	... 35 common frames omitted
datahub-gms               | 2022-02-23 16:24:43.490:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@3339ad8e{Open source GMS,/,file:///tmp/jetty-0_0_0_0-8080-war_war-_-any-1286270472308214198.dir/webapp/,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
datahub-gms               | org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.linkedin.gms.factory.common.GitVersionFactory]; nested exception is java.io.FileNotFoundException: class path resource [git.properties] cannot be opened because it does not exist
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
datahub-gms               | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:921)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:554)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:888)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:357)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1443)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1407)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:821)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
datahub-gms               | Caused by: 
datahub-gms               | java.io.FileNotFoundException: class path resource [git.properties] cannot be opened because it does not exist
datahub-gms               | 	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:180)
datahub-gms               | 	at org.springframework.core.io.support.EncodedResource.getInputStream(EncodedResource.java:159)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:99)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:73)
datahub-gms               | 	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:59)
datahub-gms               | 	at org.springframework.core.io.support.ResourcePropertySource.<init>(ResourcePropertySource.java:67)
datahub-gms               | 	at org.springframework.core.io.support.DefaultPropertySourceFactory.createPropertySource(DefaultPropertySourceFactory.java:37)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.processPropertySource(ConfigurationClassParser.java:455)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:274)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:319)
datahub-gms               | 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
datahub-gms               | 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
datahub-gms               | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
datahub-gms               | 	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
datahub-gms               | 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:921)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:554)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:888)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:357)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1443)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1407)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:821)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:276)
datahub-gms               | 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
datahub-gms               | 	at org.eclipse.jetty.server.Server.start(Server.java:407)
datahub-gms               | 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
datahub-gms               | 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
datahub-gms               | 	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
datahub-gms               | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
datahub-gms               | 	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
datahub-gms               | 2022-02-23 16:24:43.521:INFO:oejs.AbstractConnector:main: Started ServerConnector@5fdef03a{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
datahub-gms               | 2022-02-23 16:24:43.521:INFO:oejs.Server:main: Started @11102ms
datahub-gms               | 2022-02-23 16:25:03.036:WARN:oejs.HttpChannel:qtp544724190-16: /health
datahub-gms               | javax.servlet.ServletException: javax.servlet.UnavailableException: Servlet Not Initialized
datahub-gms               | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
datahub-gms               | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               | 	at org.eclipse.jetty.server.Server.handle(Server.java:494)
datahub-gms               | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
datahub-gms               | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
datahub-gms               | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
datahub-gms               | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
datahub-gms               | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
datahub-gms               | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
datahub-gms               | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
datahub-gms               | 	at java.lang.Thread.run(Thread.java:748)
datahub-gms               | Caused by: 
datahub-gms               | javax.servlet.UnavailableException: Servlet Not Initialized
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:822)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:544)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
datahub-gms               | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
datahub-gms               | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
datahub-gms               | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
datahub-gms               | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
datahub-gms               | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
datahub-gms               | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
datahub-gms               | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
datahub-gms               | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
datahub-gms               | 	at org.eclipse.jetty.server.Server.handle(Server.java:494)
datahub-gms               | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
datahub-gms               | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
datahub-gms               | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
datahub-gms               | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
datahub-gms               | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
datahub-gms               | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
datahub-gms               | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
datahub-gms               | 	at java.lang.Thread.run(Thread.java:748)
```

On a related note the sentence "simply restart the Metadata Service to start enforcing Authentication" found [here](https://datahubproject.io/docs/introducing-metadata-service-authentication/#configuring-metadata-service-authentication) is a bit unclear. First of all which service is the Metadata Service? And second restarting a Docker container has no effect on changed config parameters whatsoever.

I don't really know what to try next so any help would be appreciated.

**Comment by eeepmb** [comment]
I nuked everything and started from scratch. Closing this issue.
