### ISSUE TITLE
Error Request Header Fields Too Large

### ISSUE THREAD

**Issue by initanmol** [linkedin/datahub#4362]
I'm using Kong with OIDC as a reverse proxy to Datahub frontend service and after successful OIDC authentication, I'm getting the following error in Frontend service logs. 

```
16:49:47 [application-akka.actor.default-dispatcher-171] WARN  akka.actor.ActorSystemImpl - Illegal request, responding with status '400 Bad Request': Unsupported HTTP method: HTTP method too long (started with '￿￿�
￿￿�￿￿�'). Increase `akka.http.server.parsing.max-method-length` to support HTTP methods with more characters.
16:52:03 [application-akka.actor.default-dispatcher-261] INFO  org.eclipse.jetty.util.log - Logging initialized @1198070ms to org.eclipse.jetty.util.log.Slf4jLog
  1 # Please edit the object below. Lines beginning with a '#' will be ignored,
16:52:03 [application-akka.actor.default-dispatcher-261] WARN  application - The submitted callback is unsupported!
17:38:50 [application-akka.actor.default-dispatcher-572] WARN  application - The submitted callback is unsupported!
17:38:50 [application-akka.actor.default-dispatcher-572] ERROR controllers.AuthenticationController - Authentication error
javax.naming.AuthenticationException: javax.security.auth.login.FailedLoginException
	at security.AuthenticationManager.authenticateUser(AuthenticationManager.java:29)
	at controllers.AuthenticationController.logIn(AuthenticationController.java:129)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:380)
	at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$5$$anonfun$apply$5.apply(Routes.scala:380)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:134)
	at play.core.routing.HandlerInvokerFactory$$anon$3.resultCall(HandlerInvoker.scala:133)
	at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$8$$anon$2$$anon$1.invocation(HandlerInvoker.scala:108)
	at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:88)
	at play.http.DefaultActionCreator$1.call(DefaultActionCreator.java:31)
	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
	at play.core.j.JavaAction$$anonfun$9.apply(JavaAction.scala:138)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:56)
	at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
	at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:48)
	at scala.concurrent.impl.Future$.apply(Future.scala:31)
	at scala.concurrent.Future$.apply(Future.scala:494)
	at play.core.j.JavaAction.apply(JavaAction.scala:138)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:96)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:89)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:92)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:92)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
17:39:01 [application-akka.actor.default-dispatcher-572] WARN  application - The submitted callback is unsupported!
17:46:34 [application-akka.actor.default-dispatcher-654] WARN  akka.actor.ActorSystemImpl - Illegal request, responding with status '431 Request Header Fields Too Large': HTTP header value exceeds the configured limit of 8192 characters
17:46:35 [application-akka.actor.default-dispatcher-654] WARN  akka.actor.ActorSystemImpl - Illegal request, responding with status '431 Request Header Fields Too Large': HTTP header value exceeds the configured limit of 8192 characters
```

To resolve the above issue, I'm looking for a way to increase request header size but am not able to find an appropriate configuration option. Please help me with it.

This Datahub setup was done on AWS using [this](https://datahubproject.io/docs/deploy/aws/) guide

**Comment by initanmol** [comment]
I was able to fix this issue by adding `-Dplay.server.akka.max-header-value-length=16k` to `JAVA_OPTS` env variables defined at https://github.com/linkedin/datahub/blob/master/docker/datahub-frontend/env/docker.env#L6
