### ISSUE TITLE
_handle_execute() error during assertion.

### ISSUE THREAD

**Issue by WaStCo** [linkedin/datahub#4389]
We are experiencing some weird errors during profiling that were not present before this PR. Basically, our query returns a string object and hence fails the assertion. Before, _handle_execute() catched this situation by returning False, None in this case.

_Originally posted by @WaStCo in https://github.com/linkedin/datahub/pull/3674#r824836313_

**Comment by WaStCo** [comment]
Traceback for the error:

`[2022-03-10 07:20:01,838] {sqlalchemy_query_combiner.py:247} ERROR - Failed to execute query normally, using fallback: SELECT pr_id 
FROM ttrack.sst_lots_scan 
WHERE 1 = 1 AND pr_id IS NOT NULL
AND ROWNUM <= 20
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 114, in get_query_columns
    inner_columns = list(query.inner_columns)
AttributeError: 'str' object has no attribute 'inner_columns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 243, in _sa_execute_fake
    handled, result = self._handle_execute(conn, query, args, kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 214, in _handle_execute
    if not self.is_single_row_query_method(query):
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 302, in _is_single_row_query_method
    query_columns = get_query_columns(query)
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 117, in get_query_columns
    return list(query.columns)
AttributeError: 'str' object has no attribute 'columns'`

**Comment by WaStCo** [comment]
Maybe something like:
metadata-ingestion/src/datahub/utilities/sqlalchemy_query_combiner.py Line 216:
```
        # Figure out how many columns this query returns.
        # This also implicitly ensures that the typing is generally correct.
        try:
            assert len(get_query_columns(query)) > 0
        except:
            return False, None
```

**Comment by hsheth2** [comment]
@WaStCo - yep that seems like a reasonable fix, although we might want to tighten it to `except AttributeError:`. Do you want to open a PR?

In the interim, you can set `profiling.query_combiner_enabled` to false to avoid this issue.

**Comment by WaStCo** [comment]
Hi @hsheth2, thank you for the fast reply. I will propose that in our case we disable the query combiner globally, this will sove our issues. Since we only have this Oracle DB throwing an error in this place,  I am unsure in how far I could tighten the AttributeError (well, in our case query contains a plain str - but this might be too specific for other instances).

If the colleagues are fine with disabling the query combiner on monday, I'll close this issue. Unless you are fine with the AttributeError and testing for str, then I'll gladly open a PR.

Best, Wagner
