### ISSUE TITLE
Problems encountered in intranet deployment of datahub

### ISSUE THREAD

**Issue by persistZzzZ** [linkedin/datahub#4402]
2022/03/14 07:14:25 Problem with request: Get "http://datahub-gms:8080/health": dial tcp 172.18.0.7:8080: connect: connection refused. Sleeping 1s
2022/03/14 07:14:26 Problem with request: Get "http://datahub-gms:8080/health": dial tcp 172.18.0.7:8080: connect: connection refused. Sleeping 1s
2022/03/14 07:14:28 Received 200 from http://datahub-gms:8080/health
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f5572ddcd60>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5572ddcd60>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 615, in _write_request
    response = self._session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5572ddcd60>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/datahub", line 5, in <module>
    from datahub.entrypoints import main
  File "/usr/local/lib/python3.9/site-packages/datahub/entrypoints.py", line 11, in <module>
    from datahub.cli.delete_cli import delete
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/delete_cli.py", line 21, in <module>
    from datahub.telemetry import telemetry
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 147, in <module>
    telemetry_instance = Telemetry()
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 46, in __init__
    mp.people_set(
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 238, in people_set
    return self.people_update({
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 392, in people_update
    self._consumer.send('people', json_dumps(record, cls=self._serializer))
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 594, in send
    self._write_request(self._endpoints[endpoint], json_message, api_key, api_secret)
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 623, in _write_request
    six.raise_from(MixpanelException(e), e)
  File "<string>", line 3, in raise_from
mixpanel.MixpanelException: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5572ddcd60>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
2022/03/14 07:15:08 Command exited with error: exit status 1
2022/03/14 07:32:41 Waiting for: http://datahub-gms:8080/health
2022/03/14 07:32:41 Received 200 from http://datahub-gms:8080/health
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f83ed1b3910>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f83ed1b3910>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 615, in _write_request
    response = self._session.post(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f83ed1b3910>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/datahub", line 5, in <module>
    from datahub.entrypoints import main
  File "/usr/local/lib/python3.9/site-packages/datahub/entrypoints.py", line 11, in <module>
    from datahub.cli.delete_cli import delete
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/delete_cli.py", line 21, in <module>
    from datahub.telemetry import telemetry
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 147, in <module>
    telemetry_instance = Telemetry()
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 46, in __init__
    mp.people_set(
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 238, in people_set
    return self.people_update({
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 392, in people_update
    self._consumer.send('people', json_dumps(record, cls=self._serializer))
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 594, in send
    self._write_request(self._endpoints[endpoint], json_message, api_key, api_secret)
  File "/usr/local/lib/python3.9/site-packages/mixpanel/__init__.py", line 623, in _write_request
    six.raise_from(MixpanelException(e), e)
  File "<string>", line 3, in raise_from
mixpanel.MixpanelException: HTTPSConnectionPool(host='api.mixpanel.com', port=443): Max retries exceeded with url: /engage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f83ed1b3910>, 'Connection to api.mixpanel.com timed out. (connect timeout=10)'))
2022/03/14 07:33:22 Command exited with error: exit status 1

**Comment by persistZzzZ** [comment]
My server cannot access the public network, so I encountered the above error when deploying datahub with docker

**Comment by anshbansal** [comment]
This was fixed a few days ago. Can you please try with a new CLI version?

**Comment by persistZzzZ** [comment]
> This was fixed a few days ago. Can you please try with a new CLI version?

thanks ，

**Comment by maggiehays** [comment]
Hi @persistZzzZ, thanks for pushing this issue! We'll close it out for now, but please feel free to open a new issue if upgrading to the newest CLI doesn't do the trick.
